from googletrans import Translator

translator = Translator()
# result = translator.translate('Пригоди', src='uk', dest='en')

genres_dict = {'"Драма"': '"drama"', '"Мистецтво"': '"art"', '"Військовий"': '"military"', '"Трагедія"': '"tragedy"',
               '"Фантастика"': '"fantasy"', '"Кримінал"': '"crime"', '"Анімація"': '"animation"',
               '"Мюзикл"': '"musical"', '"Спорт"': '"sport"', '"Детектив"': '"detective"',
               '"Містика"': '"mysticism"', '"Балет"': '"ballet"', '"Вестерн"': '"western"', '"Трилер"': '"thriller"',
               '"Екшн"': '"action"', '"Біографічний"': '"biographical"', '"Романтика"': '"romance"',
               '"Мультфільм"': '"cartoon"', '"Концерт"': '"concert"', '"Мелодрама"': '"melodrama"',
               '"Фентезі"': '"fantasy"', '"Жахи"': '"horrors"', '"Комедія"': '"comedy"',
               '"Документальний"': '"documentary"', '"Сімейний"': '"family"', '"Історичний"': '"historical"',
               '"Бойовик"': '"action"', '"Пригоди"': '"adventure"', '"Театр"': '"theater"',
               '"Спектакль"': '"performance"'}

countries_dict = {'': '""', '"Australia"': '"Australia"', '"France"': '"France"',
                  '"United Kingdom"': '"United Kingdom"', '"CША"': '"USA"', '"USA"': '"USA"', '"Germany"': '"Germany"',
                  '"Грузія"': '"Georgia"', '"Україна"': '"Ukraine"', '"Франція"': '"France"',
                  '"Великобританія"': '"United Kingdom"', '"Малайзія"': '"Malaysia"', '"Індія"': '"India"',
                  '"Чехія"': '"Czech"', '"США"': '"USA"', '"Велікобританія"': '"United Kingdom"',
                  '"Нідерланди"': '"Netherlands"', '"Японія"': '"Japan"', '"Гонконг"': '"Hong Kong"',
                  '"Північна Македонія"': '"Northern Macedonia"', '"Кенія"': '"Kenya"', '"Польща"': '"Poland"',
                  '"Великобритания"': '"United Kingdom"', '"Велика Британія"': '"United Kingdom"',
                  '"Литва"': '"Lithuania"', '"Бельгія"': '"Belgium"', '"Мексика"': '"Mexico"',
                  '"Маврикій"': '"Mauritius"', '"Південна Корея"': '"South Korea"', '"Люксембург"': '"Luxembourg"',
                  '"Болгарія"': 'Bulgaria', '"Німеччина"': '"Germany"', '"Швеція"': '"Sweden"',
                  '"Колумбія"': '"Colombia"', '"Франция"': '"France"', '"Туніс"': '"Tunisia"',
                  '"Нова Зеландія"': '"New Zealand"', '"ПАР"': '"South Africa"', '"Норвегія"': '"Norway"',
                  '"Росія"': '"Russia"', '"Італія"': '"Italy"', '"Іспанія"': '"Spain"', '"Латвія"': '"Latvia"',
                  '"Фінляндія"': '"Finland"', '""': '""', '"Австрія"': '"Austria"', '"Китай"': '"China"',
                  '"Угорщина"': '"Hungary"', '"Ірландія"': '"Ireland"', '"Перу"': '"Peru"', '"ОАЕ"': '"OAU"',
                  '"Данія"': '"Denmark"', '"Андорра"': '"Andorra"', '"Ісландія"': '"Iceland"', '"Англія"': '"England"',
                  '"United States"': '"USA"', '"Канада"': '"Canada"', '"Аргентина"': '"Argentina"',
                  '"Румунія"': '"Romania"', '"Italy"': 'Italy', '"Австралія"': '"Australia"'}

directors_dict = {'"Тейлор Шерідан"': '"Taylor Sheridan"', '"Керрі Крекнелл"': 'Kerry Cracknell',
                  '"Мартін Котік"': '"Martin Kotik"', '"Пітер Хеджес"': '"Peter Hedges"',
                  '"Девід Бетті"': '"David Betty"', '"Франческо Міччіке"': '"Francesco Mikchiki"',
                  '"Жак Клюгер"': '"Jacques Klyuger"', '"Сем Левінсон"': '"Sam Levinson"',
                  '"Людовик Кольбо-Жюстен"': '"Louis Colso-Justen"', '"Віктор Левін"': '"Victor Levin"',
                  '"Террі Гілліам"': '"Terry Gilliam"', '"Сем Мендес"': '"SEM Mendes"',
                  '"Мартін Кемпбелл"': '"Martin Campbell"', '"Тобі Генкель"': '"Toby Henkel"',
                  '"Девід Беніофф"': '"David Benioff"', '"Метт Аселтон"': '"Matt Asselton"',
                  '"Жак Одіар"': '"Jacques Odar"', '"Пiтер Джексон"': '"Jackson Middle"', '"Еббі Кон"': '"Ebby Kon"',
                  '"Адам Мейсон"': '"Adam Mason"', '"Девід Літч"': '"David Litch"', '"Пол Кінг"': '"Paul King"',
                  '"Ґевін Гуд"': '"Gavin Gud"', '"Вілл Глак"': '"Will Glac"',
                  '"Алі Самаді Ахаді"': '"Ali Samadi Ahadi"', '"Wes Anderson"': '"Ves Anderson"',
                  '"Валері Донзеллі"': '"Valery Donzelli"', '"Орен Муверман"': '"Oren Muverman"',
                  '"Jaume Collet-Serra"': '"Jaome Tsel-Serra"', '"Антон Сігурдссон"': '"Anton Sigurdsson"',
                  '"Ріхард Клаус"': '"Richard Claus"', '"Федеріко Фелліні"': '"Federico Fellini"',
                  '"Нікі Каро"': '"Niki Karo"', '"Том Вольф"': '"Tom Wolf"', '"Руне Спаанс"': '"Rune Spaance"',
                  '"Джош Кулі"': '"Josh Balls"', '"Дакота Ґорман"': '"Dakota Gorman"',
                  '"Поллі Фіндлі"': '"Pollie Findley"', '"Дженніфер Весткотт"': '"Jennifer Westkott"',
                  '"Олив\'є Барру"': '"Olives of Barrier"', '"Брайан Хенсон"': '"Brian Henson"',
                  '"Річард Фінн"': '"Richard Finn"', '"Марк Вільямс"': '"Mark Williams"',
                  '"Майкл Алмерейда"': '"Michael Almerida"', '"Леос Каракс"': '"Leos Carax"',
                  '"Дяо Інань"': '"Dyo Inan"',
                  '"Кен Сензель"': '"Ken Sensel"', '"Дані Леві"': '"Levi data"', '"Селін Сьямма"': '"Selin Sueshamma"',
                  '"Джефф Уодлоу"': '"Jeff Wadlow"', '"Лорін Скафарія"': '"Lorin Scaparia"',
                  '"Майкл Поліш"': '"Michael Polish"', '"Джонатан Хопкінс"': '"Jonathan Hopkins"',
                  '"Бальтасар Кормакур"': '"Baltasar Cormocrow"', '"Гіл Юнгер"': '"Gil Junger"',
                  '"Рон Шелтон"': '"Ron Shelton"', '"Джозі Рурк"': '"Jozi Rourke"', '"Ентоні Бірн"': '"Anthony Byrn"',
                  '"Ґрант Сп\'ютор"': '"Grant Taptur"', '"Росс Кларк"': '"Ross Clark"',
                  '"М. Найт Ш’ямалан"': '"M. Knight Shpaamalan"', '"Режі Ройнсар"': '"Rigging Roinsar"',
                  '"Франческо Інверніцці"': '"Francesco Invernitski"', '"Мартін Скорсезе"': '"Martin Scorsese"',
                  '"Енді Фікмен"': '"Andy Fikmen"', '"Уес Болл"': '"Wes Ball"', '"Чак Пауерс"': '"Chuck Powers"',
                  '"Метью Каллен"': '"Matthew Cullen"', '"Перрі Ленг"': '"Perry Lang"',
                  '"Джулія Дюкорно"': '"Julia Duhorno"', '"Декстер Флетчер"': '"Dexter Fletcher"',
                  '"Лу Жене"': '"Lu Gene"', '"Джастін Курзель"': '"Justin Curzel"',
                  '"Уош Уестмоленд"': '"Wash Westmoland"', '"Мілош Форман"': '"Milos Foreman"',
                  '"Девід Хекл"': '"David Hekl"', '"Алістер Грірсон."': '"Alistair Grirson."',
                  '"Франсуа Озон"': '"Francois Ozon"', '"Клеа ДюВалл"': '"Clae Dwal"',
                  '"Боб Персічетті"': '"Bob Persicetti"', '"Лаям Гевін"': '"Layam Gevin"',
                  '"Крейґ Ґіллеспі"': '"Craig Gillespaper"', '"Ерік Толедано"': '"Eric Toledano"',
                  '"Баз Лурман"': '"Bases Lorman"', '"Крістіан Волькман"': '"Christian Volkman"',
                  '"Лін Одінг"': '"Lin Oding"', '"Ролан Еммеріх"': '"Rolan Emmerich"',
                  '"Чандрасекаран"': '"Chandrasecaran"', '"Карл Стреті"': '"Carl Streets"',
                  '"Майкл Доерті"': '"Michael Derti"', '"Джастін Бенсон"': '"Justin Benson"',
                  '"Пітер Хатчингс"': '"Peter Hatchings"', '"Кім Фаррант"': '"Kim Farant"',
                  '"Андрес Фаєль"': '"Andres Fayel"', '"Ліам О’Доннелл"': '"Liam O\'Donnell"',
                  '"Росс Венокур"': '"Ross Venokur"', '"Дестін Креттон"': '"Destin Cretton"',
                  '"Рон Скальпелло"': '"Ron Scalpello"', '"Маріт Мум Оне"': '"Marit Mum On"',
                  '"Максим Говаре"': '"Maxim Govare"', '"Felix van Groeningen"': '"Felih Van Groningen"',
                  '"Тім Трахте"': '"Tim trache"', '"Денні Бойл"': 'Daily Boyle', '"Мігель Артета"': '"Miguel Arteta"',
                  '"Йон Сан-хо"': '"Jon San Ho"', '"П\'єр Шоллер"': 'Pierre Sholler "', '"Ирина Цилик"': '"Irina CILL"',
                  '"Ян Чон-вунг"': '"Yan Chon-Vung"', '"Сільві Оайон"': '"Silvi District"',
                  '"Дженсен Ноен"': '"Jensen Noeen"', '"Патрік Х\'юз"': '"Patrick Hughes"',
                  '"Мамору Хосода"': '"Mammorro Hosoda"', '"Мішель Ларок"': '"Michel Larco"',
                  '"Даґ Лайман"': '"Dag Lymeman"', '"Брендон Крістенсен"': '"Brandon Kristensen"',
                  '"Джеймса Менґолд"': '"James Mengold"', '"Робін Суїкорд"': '"Robin Suikord"',
                  '"Адам МакКей"': '"Adam Mackay"', '"Destin Daniel Cretton"': '"Destin Daniel Tsretoton"',
                  '"Крістоффер Бое"': '"Cristoffer Boe"', '"Michael Chaves"': '"Michael Chavez"',
                  '"Девід Ф. Сандберг"': '"David F. Sandberg"', '"Білл Голдермен"': '"Bill Golder"',
                  '"Шейн Блек"': '"Shane Black"', '"Пітер Лепеніотіс"': '"Peter Lepeniotis"',
                  '"Роб Маршалл"': '"Rob Marshall"', '"Джон Лукас"': '"John Lucas"',
                  '"Леопольдо Агіляр"': '"Leopold Agiber"', '"Вільям Брент Белл"': '"William Brent Bell"',
                  '"Майкл Саксі"': '"Michael Saxi"', '"Паскаль Ложьє"': '"Pascal Lozier"',
                  '"Джейсон Лей Гоуден"': '"Jason Lei Gouden"', '"Джейсон Кеббел"': '"Jason Kebbel"',
                  '"Лоран Тірар"': '"Laurent Tirar"', '"Хав\'єр Фессер"': '"Javier Fesser"',
                  '"Will Sharpe"': '"HIV Charpe"', '"С. Крейг Залер"': '"S. Craig Zaler"',
                  '"Стівен Кейпл мл."': '"Stephen Cape ml."', '"Руперт Ваят"': '"Rupert Vayat"',
                  '"Ісіда Хіроясу"': '"Isida of Chirayas"', '"Джона Фейнґолд"': '"John Feyngold"',
                  '"Гай Річі"': '"Guy Richie"', '"Джеремі Херрін"': '"Jeremy Herrin"',
                  '"Джонатан Баттерелл"': '"Jonathan Batterell"', '"Закарі Адлер"': '"Zakari Adler"',
                  '"Дін Парізо"': '"Dean Pariso"', '"Еліз Дюран"': '"Eliz Duran"', '"Джеймс Ван"': '"James Wang"',
                  '"Міккель Бренне Сандемусе"': '"Mikkel Brenne Sandemus"', '"Шарунас Бартас"': '"Sharunas Bartas"',
                  '"Бред Бьорд"': '"Brad Bjard"', '"Білл Кондон"': '"Bill Condon"', '"Теа Шеррок"': '"Tea Shherourk"',
                  '"Ерік Тості"': '"Eric toast"', '"Малкольм Д. Лі"': '"Malcolm D. Lee"',
                  '"Джастін Дж. Дік"': '"Justin J. Dick"', '"Олександр Пейн"': 'Alexander Paine',
                  '"Френсіс Лі"': '"Francis Lee"', '"Каллен Брункер"': '"Cullen Brunker"',
                  '"Ермініо Перокко"': '"Erminio Pyroko"', '"Армандо Іонуччі"': '"Armando Ionucci"',
                  '"Ерік Шмітт"': '"Eric Schmitt"', '"Ян Бубенічек"': '"Yang Bubenichek"',
                  '"Едуардо Шульдт"': '"Eduardo Schuldt"', '"Річард Дейл"': '"Richard Dale"',
                  '"Олександр Ажа"': 'Alexander Aja "', '"Йоахим Тріер"': '"Joahim Trier"',
                  '"Томас Безуча"': '"Thomasless"', '"Едуардо Гонделл"': '"Eduardo Gondell"',
                  '"Джеймс Ґрей"': '"James Gray"', '"Кеннет Брана"': '"Kenneth Brana"',
                  '"Хайфа Аль-Мансор"': 'Haifa Al-Mansor', '"Саймон Кертіс"': '"Simon Curtis"',
                  '"Бен Луін"': '"Ben Lin"', '"Пол У.С Андерсон"': '"Paul U.S Anderson"',
                  '"Кім Хаген Єнсен"': '"Kim Hagen Yensen"', '"Ендрю Левітас"': '"Andrew Levitas"',
                  '"Chris Columbus"': '"Church of Tsolombus"', '"Пітер Берг"': '"Peter Berg"',
                  '"Макс Мінгелла"': '"Max Mingell"', '"Маттео Гарроне"': '"Matteo Garron"',
                  '"Майкл Гої"': '"Michael Goy"', '"Гарі Доберман"': '"Gary Doberman"', '"Ромен Кіро"': '"Ramen Kiro"',
                  '"Тейт Тейлор"': '"Tait Taylor"', '"Пітер Джексон': '"Peter Jackson',
                  '"Мунія Меддур"': '"Munia Meddur"', '"Director Ray Manzarek"': '"Director Paradise Manzarek"',
                  '"Клер МакКарті"': '"Claire McCarthy', '"Флоріан Давід Фіц"': '"Florian David Fit"',
                  '"Тьєррі Донар"': '"Thierry Donar"', '"Мартін Сендв’єт"': '"Martin Sandwiet"',
                  '"Jon M. Chu"': '"Jon M. Chu"', '"Урсула Макфарлейн"': '"Ursula McFarlein"',
                  '"Чад Стахелські"': '"Chad Stagle"', '"Сторм Ешвуд"': '"Storm Ashwood"', '"Шон Сіт"': '"Sean Sits"',
                  '"Алессандро Карлоні"': '"Alessandro Charlony"', '"Джонатан Генслі"': '"Jonathan Genly"',
                  '"Кевін Джонсон"': '"Kevin Johnson"', '"Бенедикт Ерлінгссон"': '"Benedict Erlingsson"',
                  '"Фатіх Акін"': '"Fatih Akin"', '"Тім Сторі"': '"Tim Port"', '"Майк П. Нельсон"': '"Mike P. Nelson"',
                  '"Домінік Абель"': '"Dominique Abel"', '"Янн Артус-Бертран"': '"Jann Artus-Bertrand"',
                  '"Ладіслас Шолла"': '"Ladislas Schola"', '"Рашид Бушареб"': '"Rashid Busharb"',
                  '"Ален Шаба"': '"Alen Shaba"', '"Джерард Буш"': '"Gerard Bush"',
                  '"Девід Йетс"': '"David Yets"', '"Пол Дано"': '"Paul Dano"', '"Стефано Солліма"': '"Stephano Silima"',
                  '"Флоріан Зеллер"': '"Florian Zeller"', '"Лі Айзек Чунг"': '"Lee Isec Chung"',
                  '"Апічатпонг Вірасетакул"': '"Apichatpong Virsetakul"', '"Ніколас Песке"': '"Nicholas Pesskey"',
                  '"Майкл Мелскі"': '"Michael Melki"', '"Клайв Тонж"': '"Clive Tonzh"',
                  '"Софія Такал"': '"Sofia Takal"', '"Ден Скенлон"': '"Dan Scenon"', '"Марк Тойя"': '"Mark Axi"',
                  '"Горо Міядзакі"': '"Gori Miyazaki"', '"Ксав\'є Долан"': '"Xavier Dolan"',
                  '"Кларк Дьюк"': '"Clark Dyuk"', '"Jake Kasdan"': '"Which Kasdan"', '"Со Абаді"': '"CO ABADY"',
                  '"Марися Нікітюк"': '"Mary Nikitsuk"', '"Раду Жуде"': '"Board Judge"',
                  '"Девід Блер"': '"David Blair"', '"Джефф Томсіч"': '"Jeff Tomsich"',
                  '"Ганно Олдердіссен"': '"Hanno Aldersensen"', '"Will Gluck"': '"HIV Glutzk"',
                  '"Guy Ritchie"': '"Dick ritchie"', '"ЕДҐАР РАЙТ"': 'Edgar Rait"', '"Бретт Пірс"': '"Brett Pierce"',
                  '"Уес Андерсон"': '"UES Anderson"', '"Гейл Манкузо"': '"Gale Mankus"',
                  '"Стенлі Туччі"': '"Stanley Tuchchi"', '"Даніс Танович"': '"Danis Tanovich"',
                  '"Оскар Ройлер"': '"Oscar Royler"', '"Дені Аркан"': '"Deni Arkan"',
                  '"Брігітте Дродтлофф"': '"Brigitte Rodloff"', '"Рууд Шуурман"': '"Ruud Shuurman"',
                  '"Прісцилла Камерон"': '"Priscilla Cameron"', '"Андреа Берлофф"': '"Andrea Berloff"',
                  '"Патрік Уайт"': '"Patrick White"', '"Елайджа Байнум"': '"Elyja byman"',
                  '"Стівен С. Кампанеллі"': '"Stephen S. Campanelli"', '"Альбер Дюпонтель"': '"Alber Dupontel"',
                  '"Джоель Кроуфорд': '"Joel Crawford',
                  '"Пьєр-Франсуа Мартін-Лаваль"': '"Pierre-Francois Martin Laval"', '"Вілл Бечер"': '"Willer Willer"',
                  '"Девід Реймонд"': '"David Raymond"', '"Забу Брейтман"': '"Breithman\'s for you"',
                  '"Нілл Блумкамп"': '"NYLL Blummump"', '"Lana Wachowski"': '"Lana Vacovsky"',
                  '"Ларс фон Трієр"': '"Lars von Trier"', '"Пол Шредер"': '"Paul Shreder"',
                  '"Рендалл Емметт"': 'Rendall Emmett', '"Аарон Вудлі"': '"Aaron Woodley"',
                  '"Дейв Франко"': '"Dave Franco"', '"Джефф Фаулер"': '"Jeff Fowler"',
                  '"Девід Прайор"': '"David Pryor"', '"Азіф Кападіа"': '"Azif Kapadia"',
                  '"Джастін Бальдоні"': '"Justin Baldone"', '"Маркус Шляйнцер"': '"Marcus pathway"',
                  '"Іван Гільєрмо"': '"Ivan Gilermo"', '"Денис Делич"': '"Denis Delich"',
                  '"Кірбі Аткінс"': '"Kirby Atkins"', '"Жиль де Метр"': '"Gill de Meter"',
                  '"Джон Краулі"': '"John Crawley"', '"Майк Фленеган"': '"Mike Flenegan"',
                  '"Міхаель Ханеке"': '"Michael Haneke"', '"Крістофер Нолан"': '"Christopher Nolan"',
                  '"Еверардо Валеріо Ґоут"': '"Everardo Valerio Gaut"', '"Бен Фалкоун"': '"Ben Falkon"',
                  '"Дон Е. ФонтЛе Рой"': '"Don E. Fontle Roy"', '"Бен Фелкоун"': 'Ben Felkoun"',
                  '"Ніколас МакКарті"': '"Nicholas McCarty"', '"Ерве Мімран"': '"Erve Mimran"',
                  '"Деніел Коен"': '"Deniel Cohen"', '"Девід Бікерстафф"': '"David Bikerstaff"',
                  '"Кайл Ранкін"': '"Kyle Rankin"', '"Панос Косматос"': '"Panos Spotos"',
                  '"Том Едмундс"': '"Tom Edmunds"', '"Вонг Кар-Вай"': '"Wong Car-Wai"',
                  '"Марія Шрадер"': '"Maria Schrader"', '"Dean Devlin"': '"Day Devlin"',
                  '"Роусон Маршалл Тьорбер"': '"Roseon Marshall Thorber"', '"Нік Бруно"': '"Nick Bruno"',
                  '"С.К. Дейл"': '"S.K. Dale"', '""': '""', '"Лінн Саузерленд"': 'Lynn Sauzerland "',
                  '"Марк Балдо"': '"Mark Baldo"', '"Джей Роуч"': '"Jay Roach"', '"Shawn Levy"': '"Shavn Levi"',
                  '"Стівен Ол"': '"Stephen OL"', '"Енді Метьюз."': '"Andy Matthew."', '"Гуїдо К\'єза"': '"Guido Kjesa"',
                  '"Тайлер Нілсон"': '"Tyler Nilson"', '"Роберт Родрігес"': 'Robert Rodriguez',
                  '"Ursula Macfarlane"': '"Ursula Matzfarlane"', '"Сьюзан Волтер"': '"Susan Volter"',
                  '"Макото Сінкай"': '"Makoto Sinkai"', '"Фарад Сафініа"': '"Farad Safinia"',
                  '"Роберт Лукетіч"': '"Robert Lucetic"', '"Ніколя Бедос"': '"Nikola Bedos"',
                  '"Деніел Дж. Филлипс"': '"Deniel J. Filips"', '"Лі Кронін"': '"Lee Kronin"',
                  '"Хічам Хаджі"': '"Hajam Haji"', '"П\'єр Сальвадорі"': '"Pierre Salvador"',
                  '"Лізе І. Осволл"': '"Lize I. Oswall"', '"Дейв Маклін"': '"Dave McLean"',
                  '"Манель Лабіді"': '"Manel Labid"', '"Паоло Дженовезе"': '"Paolo Genovese"',
                  '"Квентін Тарантіно"': '"Quentin Tarantino"', '"Янош Жомбояі"': '"Janos Zhemboyai"',
                  '"Пол Лейден"': '"Paul Leiden"', '"Ян Деманж"': '"Jan Demany"', '"Люк Бессон"': '"Luke Besson"',
                  '"РІДЛІ СКОТТ"': '"Ridley Scott"', '"Дженніфер Ю"': '"Jennifer Yu"',
                  '"Патрік Г\'юз"': '"Patrick Guz"',
                  '"Андерс Томас Йенсен"': '"Anders Thomas Yensen"', '"Ґабріела Кавпертвейт"': '"Gabriela Kavpertwait"',
                  '"П\'єр Морель"': '"Pierre Morel"', '"Крістіан Ріверс"': '"Christian Rivers"',
                  '"Дімітрі Логотетіс"': '"Dimitri Logotetis"', '"Steven Spielberg"': '"STVV Spielberg"',
                  '"Бенедикт Ендрюс"': '"Benedict Andrews"', '"Андреа Бескон"': '"Andrea Beskon"',
                  '"James Gunn"': '"Yams Gun"', '"Матіас Мальзйо"': '"Matias Malzyo"',
                  '"Аарон Шнайдер"': '"Aaron Schneider"', '"Ніколя Ваньє"': '"Nikola Vanier"',
                  '"Антоні Кордьє"': '"Antony Cordier"', '"Джузеппе Торнаторе"': '"Giuseppe Tornatore"',
                  '"Марина Степанська"': '"Marina Stepanskaya"', '"Ара Пайая"': '"ARA PAIA"',
                  '"Мартін Шраєр"': '"Martin Shrier"', '"Сіон Соно"': '"Sion Sona"',
                  '"Бертран Бонелло"': '"Bertrand Bonello"', '"Хаяо Міядзакі"': '"Haya Miyazaki"',
                  '"Оль Паркер"': '"Ol Parker"', '"Джейсон Флемінг"': '"Jason Fleming"',
                  '"Кейт Шортланд"': 'Kate Shortland "', '"Ліно ДіСальво"': '"Lino Dissalvo"', '"І Ге"': '"And Ge"',
                  '"Rian Johnson"': '"Rian Yoginson"', '"Жауме Балаґеро"': '"Jaome Balagero"',
                  '"Едвард Дрейк"': '"Edward Drake"', '"Еван Спіліотопулос"': '"Evan Spicyotopoulos"',
                  '"Giuseppe Tornatore"': '"Giuseppe Tornator"', '"Алехандро Брюґес"': '"Alejandro Bruges"',
                  '"Джордан Піл"': '"Jordan Peel"', '"Тамура Котаро"': '"Tamura Kotaro"',
                  '"Cate Shortland"': '"Chat Shortland"', '"Адам МакДональд"': '"Adam McDonald"',
                  '"Хлоя Чжао"': '"Chloe Zhao"', '"Норберт Кайль"': '"Norbert Kail"',
                  '"Крістофер Маккуоррі"': '"Christopher McCarri"', '"Кристоф Лауенштейн"': '"Cristof Lauenstein"',
                  '"Майкл Чавес"': '"Michael Chavez"', '"Martin Scorsese"': '"Martin SzoSeese"',
                  '"Мікеланджело Антоніоні"': '"Michelangelo Antonion"', '"Блю Ліч"': '"Blue Leach"',
                  '"Д. Дж. Карузо"': '"D. J. Karusu"', '"Ейтан Роквей"': '"Eytin Rockway"',
                  '"Томер Ешед"': '"Tomer Ashed"', '"Теона Струґар Мітевська"': '"Todo Strugar Mitewskaya"',
                  '"Томмі Віркола"': '"Tommy Virkola"', '"Кевін Макдональд"': '"Kevin McDonald"',
                  '"Джуліан Шнабель"': '"Julian Shnabel"', '"Ґреґ Тірнан"': '"Greg Tirnange"',
                  '"Девід Єйтс"': '"David Jeates"', '"Андре Овредал"': '"Andre Verdal"',
                  '"Стівен Гейган"': '"Stephen Geigan"', '"Андре Еркау"': '"Andre Erkau"',
                  '"Матьє Турі"': '"Matie Tour"', '"Філіп Годо"': '"Philip God"', '"Джо Карнахан"': '"Joe Carnakhan"',
                  '"Пол Ойє"': '"Paul Oye"', '"Арон Ґодет"': '"Aron Gotet"', '"Шон Дуркін"': '"Sean Dorker"',
                  '"Жозе Паділья"': '"Jose Padilla"', '"Стівен Ґейґан"': '"Stephen Gaygan"',
                  '"Флоріан Хенкель фон Доннерсмарк"': '"Florian Henkel von DonnersMark"',
                  '"Брайан ДеКьюбеліс"': '"Brian Dequubelis"', '"Вілл Глук"': '"Will Glunk"',
                  '"Тайка Вайтіті"': '"Waika Weitity"', '"Йоргос Лантімос"': '"JORE LANTIMS"',
                  '"Денніс Ганзель"': "Dennis Hansel '", '"Пітер Канделенд"': '"Peter Candeland"',
                  '"Наталія Мещанінова"': '"Natalia Meschanin"', '"Саймон Кінберґ"': '"Simon Kinberg"',
                  '"Гаррі Клевен"': '"Harry Kleven"', '"Лукас Файгелфелд"': '"Lucas Fajelfeld"',
                  '"Браян Де Пальма"': '"Brian de Palma"', '"Едвард Нортон"': '"Edward Norton"',
                  '"Філіпп Фалардо"': '"Philippe Falardo"', '"Каутер Бен Ганія"': '"Kaother Ben Gania"',
                  '"Аластер Орр"': '"Alaster Orr"', '"Вілл Вернік"': '"Will Vernik"', '"Хелен Жиро"': '"Helen Frying"',
                  '"Раян Джонсон"': '"Rayan Johnson"', '"Марк Манден"': '"Mark Manden"',
                  '"Метт Аскем"': '"Matt Askeem"', '"Олів’є Мейру"': '"Olivier Meyru"',
                  '"Марк Ротемунд"': '"Mark Rotemund"', '"Менді Флетчер"': '"Mendy Fletcher"',
                  '"Denis Villeneuve"': '"Denis Villenuve"', '"Тревор Нунн"': '"Trevor Nunn"',
                  '"Сільвен Вайт"': 'Silven White', '"Джош Лоусон"': '"Josh Lawson"',
                  '"Неш Еджертон"': '"Nash Egerton"', '"Джон Воттс"': '"John Vots"',
                  '"Свен Унтервальдт мл."': '"Sven Unterwaldt ml."', '"Альберт Хьюз"': '"Albert Hughes"',
                  '"Ніл Маршалл"': '"Nile Marshall"', '"Анна Боден"': '"Anna Boden"',
                  '"Фелікс Гері Грей"': '"Felix Gary Gray"', '"Девід Ейр"': '"David Ayr"',
                  '"Семюель Турно"': '"Samuel Turno"', '"Дідерік Ван Ружен"': '"Didierik van Ruden"',
                  '"АДАМ РОБІТЕЛЬ"': '"Adam Robuler"', '"Джордж Ретліфф"': '"George Ratiff"',
                  '"ЕНДІ СЕРКІС \\n"': '"Andy Sirkis"', '"Ridley Scott"': '"Rare stsot"',
                  '"Стів МакКуін"': '"Steve McCain"', '"Колін МакАйвор"': '"Colin Macaivor"',
                  '"Скотт Купер"': '"Scott Cooper"', '"Еліс Веддінґтон"': '"Alice Weddington"',
                  '"Асгар Фархаді"': '"Asgar Farhadi"', '"Джуліус Ейвері"': '"Julius Avery"', '"Пол Фіг"': '"FIG."',
                  '"Ніа Дакоста."': '"Nia Dakosta."', '"Майкл Даус"': '"Michael Daus"',
                  '"Джон Красінскі"': '"John Krasinsky"', '"Фіонн Воттс"': '"Feyn Votts"',
                  '"Тім Траґезер"': '"Tim Tragueer"', '"Florian Zeller"': '"Florian Zeller"',
                  '"Тіллер Расселл"': '"Tiller Russell"', '"Луі Псіхойос"': '"Lui Psichoos"',
                  '"Серджо Манфіо"': '"Serjo Manfio"', '"Джон Медден"': '"John Madden"',
                  '"Йорґен Клюбен"': '"Yorgen Klyuben"', '"Бенні Бум"': '"Benny Bum"',
                  '"Адам Вінґард"': '"Adam Wizgrard"', '"Дін Девлін"': '"Din Devlin"',
                  '"Армандо Іаннуччі"': '"Armando iannacci"', '"Роберт Швенке"': '"Robert Shvenke"',
                  '"Джон Берардо"': '"John Berardo"', '"Донато Каррізі"': '"Donato Courry"',
                  '"Джеймс Кокс"': '"James Coke"', '"Антуан Блоссьє"': '"Antoine Block"',
                  '"Алекс Стадерманн"': '"Alex Stadermann"', '"ДЖАСТІН ЛІН"': '"Justin Lin"',
                  '"Вацлав Маргоул"': '"Vaclav Margoul"', '"Роб В. Кінґ"': '"Rob V. King"',
                  '"Рік Роман Во"': '"Rick Roman VA"', '"Леван Акін"': '"Levan Akin"', '"Оз Перкінс"': '"Oz Perkins"',
                  '"Хармоні Корін"': '"Harmony Korin"', '"Вілл Шарп"': '"Will Sharp"',
                  '"Стівен Найт"': '"Stephen Knight"', '"Сауль Свиммер"': '"Saul Svommer"',
                  '"Сергiй Вейн"': '"Serge Wayne"', '"Енді Теннант"': '"Andy Tennant"',
                  '"Яель Фарбер ТЕСТ"': '"Yael Farber Test"', '"Пол Дагдейл"': '"Paul Dagdale"',
                  '"Джеймс Фоулі"': '"James Foul is"', '"Фернандо Леон Де Араноа"': '"Fernando Leon de Aranoa"',
                  '"Бенуа Жако"': '"Benois Jaco"', '"П\'єр Греко"': 'Pierre Greek', '"Кеті Янь"': '"Katie Yang"',
                  '"Гевін Ротері"': '"Givin Roter"', '"Роберт Лоренц"': 'Robert Lorenz',
                  '"Френсіс Лоуренс"': '"Francis Lawrence"', '"Ніколас Хайтнер"': '"Nicholas Haitner"',
                  '"Кристiан Алверт"': '"Krystian Alvert"', '"Метью Борн"': '"Matthew Born"',
                  '"Станіслав Капралов"': '"Stanislav Kortral"', '"Ерік Зонка"': '"Eric Zonka"',
                  '"Жан-Франсуа Ріше"': '"Jean-Francois Rich"', '"Джастін П. Ланге"': '"Justin P. Lange"',
                  '"Andy Serkis"': '"Andes Sirkis"', '"Торд Даніельсон"': '"Torta Daneelson"',
                  '"Вім Вендерс"': '"VM Veders"', '"Джакомо Гатті"': '"Jakomo Gatti"',
                  '"Аудні Аусгейрссон"': '"Audin Ausgeersson"', '"Enrico Casarosa"': '"Enritso Tsasaros"',
                  '"Браян Велш"': '"Brian Welsh"', '"Кирило Серебренніков"': '"Cyril Serebrenikov"',
                  '"Наталія Ворожбит"': '"Natalia Vorozhibit"', '"Філ Грабски"': '"Phil Garabski"',
                  '"Марк Хаммонд"': '"Mark Hammond"', '"Джастін Пембертон"': '"Justin Pemberton"',
                  '"Чанія Баттон"': '"Chana Batton"', '"Марк Мейєрс"': '"Mark Meys"',
                  '"Peter Farrelly"': '"Peter Farelli"', '"Уко Хохендейк"': '"UKO Hokhendyk"',
                  '"Пол Верховен"': '"Paul Verkhovna"', '"Кшиштоф Кесльовський"': '"Krzysztof Kesulovsky"',
                  '"Лі Воннелл"': '"Li Vonnell"', '"Міядзакі Хаяо"': '"Miyazaki Hayao"',
                  '"Пон Джун-хо"': '"Pon Jun-Ho"', '"Ніколя Бедос': '"Nicola Bedos',
                  '"Андрес Мускетті"': '"Andres Muskti"', '"Маркус Розенмюллер"': '"Markus Rosenmüller"',
                  '"Кевін Мунро"': '"Kevin Moonro"', '"Джон Херцфельд"': '"John Herzfeld"',
                  '"Тристан Сегела"': '"Tristan Segela"', '"Отем Де Вайлд"': '"Ohem de Weild"',
                  '"Рон Юань"': 'Ron Yuan', '"Хон Сон-хо"': '"Hon Son-Ho"', '"Ніша Ганатра"': '"Niche Ganatra"',
                  '"Джеймс Бобін"': '"James Bobin"', '"Джордан Баркер"': '"Jordan Barker"',
                  '"Патрік Кассір"': '"Patrick Cassir"', '"Ліза Джой"': '"Lisa Joy"',
                  '"Віктор Косаковський"': '"Victor Kosakovsky"', '"Міхаель Ганеке"': '"Michael Ganeque"',
                  '"Стівен Долдрі"': '"Stephen Doldry"', '"Юрій Речинський"': '"Yuriy Rechinsky"',
                  '"Ерік Лартіго"': '"Eric Lartigo"',
                  '"Еміральд Феннел"': '"Emirald Fennel"', '"Вес Андерсон"': '"Ves Anderson"',
                  '"Йеспер Гансландт"': '"YESPER GANSLANDT"', '"Шон Леві"': '"Sean Levi"',
                  '"Рюхей Кітамура"': '"Ricky Kitamura"', '"Лука Гуаданьіно"': '"Luka Guadagnino"',
                  '"Філіпп Де Шоврон"': '"Philippe de Shavoron"', '"Джо Райт"': '"Joe Wright"',
                  '"Дрю Пірс"': '"Drew Pierce"', '"Пітер Сігал"': '"Peter Sigal"',
                  '"Томас Вінтерберґ"': '"Thomas Winterberg"', '"Ешом Нелмс"': '"Eshome NELMS"',
                  '"Флюза Фархшатова"': '"Flucta FarnShivat"', '"Роберт Будро"': 'Robert Bucket',
                  '"Шон Бейкер"': '"Sean Baker"', '"Торстен Кюнстлер"': '"Torsten Kunstler"',
                  '"Крістіан Хаас"': '"Christian Haas"', '"Тім Міллер"': '"Tim Miller"',
                  '"Франк Дюбоск"': '"Frank Dubok"', '"Деррік Борте"': '"Derrick Borte"',
                  '"Todd Haynes"': '"Todd Hines"', '"Даніель Арбіден"': '"Daniel Arbiden"',
                  '"Ендрю Лоуренс"': '"Andrew Lawrence"', '"Віктор Сейнт Макарі"': '"Victor Saint Macari"',
                  '"Арі Астер"': '"Ary Aster"', '"Галина Міклінова"': '"Galina Milkin"',
                  '"Майк Мітчелл"': '"Mike Mitchell"', '"Тодд Дуглас Міллер"': '"Todd Douglas Miller"',
                  '"Андреа Ді Стефано"': '"Andrea di Stefano"', '"Ребекка Злотовські"': '"Rebecca Zotovsky"',
                  '"Кейт Вайтбред"': '"Kate Weitbred"', '"Зої Лістер Джонс"': '"Zoe Lister Jones"',
                  '"Еліо Еспанья"': '"Elio Espanya"', '"Патрік Брайс"': '"Patrick Bryce"',
                  '"Матьє Кассовіц"': '"Matie Cassowitz"', '"Деш Шоу"': '"Dash Show"',
                  '"Гільєрмо дель Торо"': '"Hillermo del Toro"', '"Алі Рей"': '"Ali Ray"',
                  '"Рідлі Скотт"': '"Ridley Scott"', '"Дж. Блейксон"': '"J. Blakeson"',
                  '"Дрейк Дорімус"': '"Drake Dorimus"', '"Енді ДеЕммоні."': '"Andy Deemmon."',
                  '"David Lowery"': '"David Lowery"', '"Ніколаус Лейтнер"': '"Nikolaus Leithner',
                  '"Родо Саягес"': '"Rodo Sayages"', '"Вінсент Д’Онофріо"': '"Vincent d\'ionfrio"',
                  '"Домінік Кук"': '"Dominique Cook"', '"Нанея Міята"': '"Nanea Miyata"',
                  '"Мей ель-Тухі"': '"Mei El Tuchi"', '"Ділан Браун"': '"Dylan Brown"', '"Джеймс Ґанн"': '"James Gann"',
                  '"Джон Тертелтауб"': '"John Terteltaub"', '"Кріс Еддісон"': '"Chris Eddison"',
                  '"Шон Андерс"': '"Shaun Anders"', '"Тоні Червоне"': '"Tony red"',
                  '"Атле Солберґ Блаксет"': '"Salberg Blueberg"', '"Девід Керр"': '"David Kerr"',
                  '"Майкл Уіннік"': '"Michael Winik"', '"Марк Ракко"': '"Mark Rakko"', '"Ніл Берґєр"': '"Neil Bergier"',
                  '"Джефф Водлоу"': '"Jeff Vodlów"', '"Серж Бозон"': '"Serge Bozon"',
                  '"Джонатан Левін"': '"Jonathan Levin"', '"Робін Райт"': '"Robin Wright"',
                  '"Майкл Ріанда"': '"Michael Rianda"', '"Йоханнес Робертс': '"Johannes Roberts',
                  '"Джеймі Беббіт"': '"Jamie Babbit"', '"Майкл Девід Пейт"': '"Michael David Peats"',
                  '"Джон М. Чу"': '"John M. Chu"', '"Джон Своб"': '"John Fob"',
                  '"Адам Іджипт Мортімер"': '"Adam Igipt Mortimer"', '"М. НАЙТ Ш\'ЯМАЛАН"': '"M. Knight Shpamalan"',
                  '"Маркус Овнелль"': '"Marcus Ovoll"', '"Дзінтарс Дрейбергс"': '"Dzintars Dreibergs"',
                  '"Жан-Філіп Віне"': '"Jean-Philip Vones"', '"Девід Яровескі"': '"David Yaroviski"',
                  '"Алексіс Міхалік"': '"Aleksis Michalyry"', '"О Юн-тон"': '"O Jun Ton"',
                  '"Джонні Мартін"': '"Johnny Martin"', '"Елейн Боґан"': '"Elaine Bogan"',
                  '"Джейк Скотт"': '"Jake Scott"', '"Том Тиквер"': '"Tom Tikver"', '"Джеймс Крамп"': '"James Cramp"',
                  '"Крістіан Петцольд"': '"Christian Petzold"', '"КРІСТОФЕР ЛЕНДОН"': '"Christopher Lendon"',
                  '"Ніл Бергер"': '"Neil Berger"', '"Гаспар Ное"': '"Gasparo Noe"', '"Lisa Joy"': '"Lisa Yoy"',
                  '"Кейсі Аффлек"': '"Casey Afflek"', '"Ксав\'є Джакометті"': '"Xavier jacoeetti"',
                  '"Андерс Вальтер Хансен"': '"Anders Walter Hansen"', '"Ґебріел Рендж"': '"Gebriel Rends"',
                  '"Андреас Дрезен"': '"Andreas Drezen"', '"Брайан А Міллер"': '"Brian A Miller"',
                  '"Гаррі Грінбергер"': '"Harry Greenberger"', '"Джон Френсіс Дейлі"': '"John Francis Daley"',
                  '"Олів\'є Ассаяс"': '"Olivier Assayas"', '"Лоуренс Фаулер"': '"Lawrence Fowler"',
                  '"Девід Фрейн"': '"David Frein"', '"Адріан Гарсія Больяно"': '"Adrian Garcia Bolano"',
                  '"Брайан Сінгер"': '"Brian Singer"', '"Вільям Юбенк"': '"William Jubenko"',
                  '"Джейкоб Шух"': '"Jacob Shush"', '"Тім Бартон"': '"Tim Barton"',
                  '"Педро Альмодовар"': '"Pedro Almodovar"', '"Адріан Грюнберг"': '"Adrian Grünberg"',
                  '"Гай Річі – "Джентльмени""': '"Guy Richie -" Gentlemen ""',
                  '"Кері Кіркпатрік"': '"Kary Kirkpatrick"', '"Тангі де Кермель"': '"Tangie de Cermel"',
                  '"Ембер Роуз Сілі"': '"Ember Rose Sili"', '"Ґас Ван Сент"': '"GAS Wang Saint"',
                  '"Філіпп Лашо"': '"Philippe Lasho"', '"Отто Баферст"': '"Otto Buferest"',
                  '"Роберт Земекіс"': 'Robert Zemecis', '"Фулвіо Сестіто"': '"Fulvio Seal"',
                  '"Марко Просерпіо"': '"Marco Prosecare"', '"Робін Обер"': '"Robin Ober"',
                  '"Федеріко Альварес"': '"Federico Alvarez"', '"Арно Лемор"': '"Arno Lemor"',
                  '"Джош Транк"': '"Josh Trak"', '"Петті Дженкінс"': '"Petty Genkins',
                  '"Ліза Аддаріо"': '"Lisa Adario"',
                  '"Ентоні Марас"': '"Anthony Maras"', '"Бенуа Годбут"': '"Benois Forward"',
                  '"Куінн Лешер"': '"Quinn Lescher"', '"Джот Ріґґс"': '"Jot Rigg"', '"Тім Хілл"': '"Tim Hill"',
                  '"Тхе-юн Кім"': '"Ta-Yun Kim"', '"Malcolm D. Lee"': '"Malzzolm D. Le"',
                  '"Даніель Брюль"': '"Daniel Brül"', '"Ердал Сейлан"': '"Erdal Seylan"',
                  '"Ден Фогельман"': '"Dan Fogelman"', '"Ґері Ван"': '"Gary Wang"',
                  '"Асаф Бернштейн"': '"Asaf Bernstein"', '"Пітер Фарреллі"': '"Peter Farrelli"',
                  '"Франк Ґастамбід"': '"Frank Gastamid"', '"Іво ван Хове"': '"Ivo Wan Hoe"',
                  '"Маріель Хеллер"': '"Mariel Haller"', '"Енді Міттон"': '"Andy Mitton"', '"Джефф Чан"': '"Jeff CHAN"',
                  '"Седрік Клапіш"': '"Sedric clapish"', '"Ерік Барб\'є"': '"Eric Barbie"',
                  '"Аарон Соркін"': '"Aaron Sorkin"', '"Леонор Серай"': '"Leonor Siray"',
                  '"Маржан Сатрапі"': '"Margan satrapi"', '"Джо Корніш"': '"Joe Cornish"',
                  '"Алі Аббасі"': '"Ali Abbas"', '"Яко Баувер"': '"As Bover"', '"Міхаель Ноер"': '"Michael Neer"',
                  '"Дон Голл"': '"Don Gall"', '"Енріко Казароза"': '"Enriko barrack"', '"Фелікс Іп"': '"Felix IP"',
                  '"Райан Беллгардт"': '"Ryan Bellhardt"', '"Таня Векслер"': '"Tanya Wexler"',
                  '"Денніс Дуган"': '"Dennis Dugan"', '"Лайонел Стекті"': '"Layonel Stack"',
                  '"Майкл Грейсі"': '"Michael Gracie"', '"Бред Пейтон"': '"Brad Peyton"',
                  '"Фелікс ван Грунінген"': '"Felix Wang Gruningen"', '"Бредлі Паркер"': '"Bradley Parker"',
                  '"Скотт Спір"': '"Scott Spore"', '"John Krasinski"': '"Jon Krasinsky"',
                  '"Лаура Шредер"': '"Laura Shreder"', '"Клінт Іствуд"': '"Clint Eastwood"',
                  '"Зара Хейєс"': '"Zara Heyes"', '"Жауме Колєт-Серра"': '"Jaome Colet Serra"',
                  '"Піт Доктер"': '"Sweat dockter"', '"Майкл Пірс"': '"Michael Pierce"',
                  '"Крістіан Каріон"': '"Christian Karion"', '"Жан-Поль Саломе"': '"Jean-Paul Salome"',
                  '"Девід Еберсоул"': '"David Ebersose"', '"Лоркан Фіннеґан"': '"Larkan Finnegan"',
                  '"Крістофер Лендон"': '"Christopher Lendon"', '"Ліна Росслер"': '"Lina Rossler"',
                  '"Вікрам Ганді"': '"Vikram Gandhi"', '"Greta Gerwig"': '"Greta Gervig"',
                  '"Кія Роуч-Тернер"': '"Kiya Roach Turner"', '"Мікаель Херс"': '"Mikael Hers',
                  '"Саймон МакКуойд"': '"Simon McQuide"', '"Деон Тейлор"': '"Deon Taylor"',
                  '"Меріенн Елліотт і Том Морріс"': '"Merienne Elliott and Tom Morris"',
                  '"Філ Джонстон"': '"Phil Johnston"', '"Мартін Овен"': '"Martin Aries"',
                  '"Роджер Камбл"': '"Roger Camble"', '"Тревіс Найт"': '"Trevis Knight"', '"Кріс Рено"': '"Chris Reno"',
                  '"Сія"': '"Sia"', '"Сальво Фікарра"': '"Salvo Ficar"', '"Вон Стайн"': '"Won Stein"',
                  '"Барт Фрейндліх"': '"Bart Freandli"', '"Тодд Філліпс"': '"Todd Phillips"',
                  '"Бредлі Купер"': '"Bradley Cooper"', '"Пейтон Рід"': '"Peyton Reed"',
                  '"Рой Андерссон"': '"Roy Anderson"', '"Мартен Прово"': '"Martin Provo"',
                  '"Роб Леттерман"': '"Rob Letterman"', '"Адам Робітел"': '"Adam Robiter"',
                  '"Філіпп де Шоврон"': '"Philippe de Shavoron"', '"Лучано Лігабуе"': '"Luchano Ligabuy"',
                  '"Ендрю Боулер"': '"Andrew Bowler"', '"Хуан Антоніо Байона"': '"Juan Antonio Bayona"',
                  '"Анн Фонтен"': '"Ann Fatenten"', '"Майлз Джоріс-Пейрафіт"': '"Miles Joris Peyirafit"',
                  '"Фред Вульф"': '"Fred Wolf"', '"Леопольдо Агілар"': '"Leopold Augilar"',
                  '"Девід Гордон Грін"': '"David Gordon Green"', '"Наталья Нілова"': '"Natalia Nilova"',
                  '"Івано Де Маттео"': '"Ivano de Matteo"',
                  '"Пернілла Фішер Крістенсен"': '"Pernilla Fisher Kristensen"', '"Джилл Калтон"': '"Jill Calon"',
                  '"Ксав\'є Жан"': '"Xavier Jean"', '"Ларс Клевберг"': '"Lars Klevberg"',
                  '"Брент Доуз"': '"Brent Dose"', '"Ентоні Руссо"': '"Anthony Rousseau"',
                  '"Олександр Аст\'є"': '"Alexander Astie"', '"Лассе Халльстрем"': '"Lasse Hallstrem"',
                  '"Рубен Флейшер"': '"Ruben Fleisher"', '"Енн Флетчер"': '"Ann Fletcher"',
                  '"Наріман Алієв"': '"Nariman Aliyev"', '"Джоель Кроуфорд"': '"Joel Crawford"',
                  '"Кріс Сандерс"': '"Chris Sanders"', '"Вікі Джонс"': '"Wiki Jones"',
                  '"Ніса Гардіман"': '"Nisa Gardimen"', '"Іен Ріксон"': '"Ien Rickson"',
                  '"Р.Дж. Катлер"': '"R.J. Kutler"', '"Антуан Фукуа"': '"Antoine Fukua"',
                  '"Мішель Хазанавічус"': '"Michelle Khazanavichus"', '"Раджа Госнелл"': '"Raja Gosnell"',
                  '"Абель Ланзак"': '"Abel Lanzak"', '"Олесь Санін"': '"Oles Sanin"',
                  '"Бора Дагтекін"': '"Bohr Dagtekin"', '"Кріс Бак"': '"Chris Buck"', '"Кей Кеннон"': '"Kay Kennon"',
                  '"Стівен С. Міллер"': '"Stephen S. Miller"', '"Дженні Гейдж"': '"Jenny Gage"',
                  '"Чарльз Мартін Сміт"': '"Charles Martin Smith"', '"Кевін Коннолі"': '"Kevin Connoli"',
                  '"Азіз Джиндані"': '"Aziz Gindani"', '"Ханс Петтер Муланд"': '"Hans Petter Mule"',
                  '"Джеремі Люттер"': '"Jeremy Litter"', '"Дрю Годдард"': '"Drew Goddard"',
                  '"Хурам Ейч Аллаві"': '"Human Aich Allaw"', '"Патріша Вітлі"': '"Patricis Witlli"',
                  '"Джессіка Гауснер"': '"Jessica Gausner"', '"Генріх Бурман"': '"Henry Burman"',
                  '"Томаш Шафраньскій"': '"Tomas Sharson"', '"Кріс Рей"': '"Chris Ray"', '"Chloé Zhao"': '"Chloé zhao"',
                  '"Вальдімар Йоганнссон"': '"Waldmar Johannsson"', '"Вес Крейвен"': '"Craven WEA"',
                  '"Justin Lin"': '"Justin Lin"', '"Дін ДеБлуа"': '"Din Dembload"', '"Єва Йонеско"': '"Eva Jonesca"',
                  '"Філіпп Штьольцль"': '"Philip Shloltsl"', '"Byron Howard"': '"Biron Howard"',
                  '"Том Хупер"': '"Tom Huper"', '"Браден Р. Дуеммлер"': '"Braden R. Duemmler"',
                  '"Франческо Сінкуемані"': '"Francesco Sinemen"', '"Стенлі Тун"': '"Stanley Tuna"',
                  '"Демієн ЛеВек"': '"Demien Levek"', '"Деніел Фаррандс"': '"Deniel Farrands"',
                  '"Стівен Чбоскі"': '"Stephen Chabed"', '"Ґуставо Ернандес"': '"Gustavo Hernandes"',
                  '"Кевін Колш"': '"Kevin Kolsh"', '"Кім Нгуен"': '"Kim Nguin"', '"Майкл Чавес': '"Michael Chavez',
                  '"Рікард Куссо"': '"Ricard Cussie"', '"Джої Сильвестр"': '"Joey Sylvester"',
                  '"Джон Лі Генкок"': '"John Lee Genkok"', '"Ері Сандел"': '"Erie Sandel"', '"Лео Ляо"': '"Leo Liao"',
                  '"Кріс Дженкінс"': '"Chris Jenkins"', '"Волт Дорн"': '"Volt Dorn"',
                  '"Гарольд Пінтер"': '"Harold Pinter"', '"Метт Беттінеллі"': '"Matt Bettinelli"',
                  '"Лана Вачовські"': '"Lana Vacovsky"', '"Тарек Будалі"': '"Budal Tare"',
                  '"Даріус Мардер"': '"Darius MARDER"', '"Піт де Ріккер"': '"Pit de Ricker"',
                  '"Джордж Ґалло"': '"George Gallo"', '"Себастьян Ґут’єррес"': '"Sebastian Gutersrez"',
                  '"Пітер Стрікленд"': '"Peter Sryuckland"', '"Піррі Реджінальд Тео"': '"Pierce Rajinaldo Teo"',
                  '"Аксель Лафон"': '"Axel Laffon"', '"Уейн Робертс"': '"Wayne Roberts"',
                  '"Ніколас Джарекі"': '"Nicholas Jareci"', '"Роман  Поланскі"': '"Roman Pulansky"',
                  '"Craig Gillespie"': '"CRAG Gillespie"', '"Елай Рот"': '"Elai Roth"',
                  '"Антоніо Лукіч"': '"Antonio Lukich"', '"Валентин Васянович"': 'Valentin Vasyanovich "',
                  '"Ноель Клірі"': '"Noel Clear"', '"Пол Вайц"': '"Paul Weits"', '"Уейн Ішам"': '"Wayne Ishham"',
                  '"Ерік Казес"': '"Eric Kases"', '"Віктор Катала"': '"Victor Catala"', '"Ken Loach"': '"Ken Loach"',
                  '"Роберт Земекіс': 'Robert Zemokis', '"Філіп Штьольцль"': '"Philip Shloltsl"',
                  '"Іван Атталь"': '"Ivan Attal"', '"Мігель Сапочнік"': '"Miguel Sapochi"',
                  '"Мартін Ґіґі"': '"Martin Gigi"', '"Френсіс Аннан"': '"Francis Annan"',
                  '"Джеффрі Начманофф"': '"Jeffrey Nachmanoff"', '"Грегорі Плоткін"': 'Gregory Plotkin',
                  '"Дін Лян"': '"Dean Lian"', '"Ліза Ланґсет"': '"Lisa Lancet"',
                  '"Свен Унтервальд мл."': '"Sven Unterwald ml."', '"Джонатан Бейкер"': '"Jonathan Baker"',
                  '"Джонатан Черч"': '"Jonathan Church"', '"Діанна Агрон"': '"Dianna Agron"', '"Енг Лі"': '"Eng Lee"',
                  '"Навот Папушадо"': '"Nank Papusado"', '"Кріс Мул"': '"Chris mule"', '"Жак Демі"': '"Jacques Demi"',
                  '"Максим Ксьонда"': '"Maxim Kinta"', '"Елізабет Бенкс"': '"Elizabeth Benx"',
                  '"Джим Джармуш"': '"Jim Jarmush"', '"Деніел Робі"': '"Deniel Robi"',
                  '"Жослін ДеБоер"': '"Julie Deuber"', '"Девід Лоурі"': '"David Lowry"',
                  '"Мітці Пейроне"': '"Peyron Lifts"', '"Роджер Евері"': '"Roger Avery"',
                  '"Мартін Оуен"': '"Martin Owen"', '"Брендон Слеґлі"': '"Brandon Sleach"',
                  '"Сімен Альсвік"': '"Semin alviak"', '"Сузанна Фогель"': '"Suzanna Fogel"',
                  '"Джастін Дек"': '"Justin DEC"', '"Клаудіо Ноче"': '"Claudio Knot"',
                  '"Уте фон Мюнхов-Поль"': '"Ute von Munhov-Paul"', '"Дейв Вілсон"': '"Dave Wilson"',
                  '"Патрік Імбер"': '"Patrick Imber"', '"Браян Кірк"': '"Brian Kirk"',
                  '"Марк Форстер"': '"Mark Forster"', '"Павло Павліковський"': '"Pavlo Pavlikovsky"',
                  '"Джим Каммінґс"': '"Jim Kammints', '"Луї Гаррель"': '"Louis Garrel"',
                  '"Кріс Батлер"': '"Chris Butler"', '"Гай Гуїдо"': '"Guy Guido"', '"Шоун Ку"': '"Shown Ku"',
                  '"Жиль Леллуш"': '"Gill Lellush"', '"Амалія Несбі Фік"': '"Amalia NEW FICK"',
                  '"Корін Харді"': '"Korin Hardy"', '"Cary Joji Fukunaga"': '"The kings of her Fukunaga"',
                  '"Сет Ларні"': '"SET Larny"', '"Кен Скотт"': '"Ken Scott"', '"Дженніфер Підом"': '"Jennifer Women"',
                  '"А.Дж. Теслер"': '"A.J. Tesler"', '"Жан-Патрік Бенес"': '"Jean-Patrick Benes"',
                  '"Туроп ван Орман"': '"Tourp van Orman"', '"Маґнус фон Горн"': '"Magnus von Gorn"',
                  '"Йоханнес Робертс"': '"Johannes Roberts"', '"Волт Бекер"': '"Volt Becker"',
                  '"Едвард Голл"': '"Edward Gall"', '"Тім Фельбаум"': '"Tim Felbaum"',
                  '"Монс Морлінд"': '"Mons Molind"', '"Спайк Лі"': '"Spike Lee"', '"Філ Грабскі"': '"Phil Grabsky"',
                  '"Генндий Тартаковський"': '"Genniy Tartakovsky"', '"Грег Тірнан"': '"Greg Tirnan"',
                  '"Майкл Спіріг"': '"Michael Spot"', '"Цзоу І"': '"Tso and"', '"Taylor Sheridan"': '"Tyler Sheridan"',
                  '"Клаудіо Джованнезі"': '"Klaudio Giwannese"', '"Девід Морріс"': '"David Morris"',
                  '"Фрідріх Боем"': '"Friedrich Boem"', '"Wim Wenders"': '"WEE WENDER"',
                  '"Джейсон Райтман"': '"Jason Raitman"', '"Олівер Дейлі"': '"Oliver Daley"',
                  '"Джин Ступніцкі"': '"Gin Stupnitski"', '"Джон Шіді"': '"John Sandy"',
                  '"Дені Вільньов"': '"Deni Vilnov"', '"Ендрю Ніккол"': '"Andrew Nikkol"',
                  '"Крістоф Оноре"': '"Christophe top"', '"Adam Wingard"': '"Adam Vygard"',
                  '"Роб Севідж"': '"Rob Seeds"', '"Хоакім Роннинґ"': 'Hoakim Roningning',
                  '"Бен Стассен"': '"Ben Stasen"', '"Свен Унтервальдт мол."': '"Sven Unterwald ml."',
                  '"Фредерік Петіжан"': '"Frederick Petizhan"', '"Род Лурі"': '"Rod Lauri"',
                  '"Шон Пол Пічініно"': '"Sean Pop Picinino"', '"Джейк Кездан"': '"Jake Kedan"',
                  '"Камілло Де Марко"': '"Camillo de Marco"', '"Роджер Мішелл"': '"Roger Michell"',
                  '"Демієн Шазель"': '"Demien Shaasel"', '"Олексій Ратманський"': '"Oleksiy Ratman"',
                  '"Ґрета Ґервіґ"': '"Greta Gervig"', '"Коллін Шиффлі"': '"Collin Schiffley"',
                  '"Крістофер МакБрайд"': '"Christopher McBride"', '"Рем Керисі"': '"REM Keries"',
                  '"Ілля Найшуллер"': '"Ilya Lastuller"', '"Габріела Вальтер"': '"Gabriela Walter"',
                  '"Леннарт Рафф"': '"Lennart Raff"', '"Сет Ґрін"': '"SET Green"', '"Дені Бун"': '"Deni Bun"',
                  '"Сем Ґарбарскі"': '"Sam Garbarsky"', '"Пітер Джексон"': '"Peter Jackson"',
                  '"Том О’Делл"': '"Tom O\'Dell"', '"Гері Росс"': '"Gary Ross"', '"Клер Дені"': '"Claire Deni"',
                  '"Крейг Гіллеспі"': '"Craig gillespaper"', '"Том МакҐрат"': '"Tom McGrat"',
                  '"Арно Борон"': '"Arno harrow"', '"Лінн Ремсі"': '"Lynn Remsi"', '"Енді Серкіс"': '"Andy Sirkis"',
                  '"Steven Soderbergh"': '"STVEN Soderberg"', '"Еміліо Портес"': '"Emilio Ports"',
                  '"Тімоті Вудворд-мл"': '"Timothy Woodward-ml"', '"Памела Б. Грін"': '"Pamela B. Green"',
                  '"Девід Лінч"': '"David Lynch"', '"Лі Уоннелл"': '"Lee UNNell"', '"Джеймс Франко"': '"James Franco"',
                  '"Руперт Ґулд"': '"Rupert Gould"', '"М. Дж. Бассетт"': '"M. J. Bassett"',
                  '"Simon McQuoid"': '"Simon Mpschouid"', '"Боб Фішер"': '"Bob Fisher"',
                  '"Девід Сілверман"': '"David Silverman"', '"Даррен Лінн Боусман"': '"Darren Lynn Bowman"',
                  '"Ніколас Хайтер"': '"Nicholas Heater"', '"Донован Марш"': '"Donovan Marsh"',
                  '"Том Харпер"': '"Tom Harper"', '"Давід Пужоль"': '"David Pujol"',
                  '"Малгожата Шумовська"': '"Malgozhato Shumovskaya"', '"Ніколя Кюш"': '"Nicola Kyush"',
                  '"Фенар Ахмад"': '"Fenar Ahmad"', '"Кері Фукунага"': '"Kerie Fukunaga"',
                  '"Антуан Віткін"': '"Antoan Witkin"', '"Ніл Армфілд"': '"Nile Armfield"',
                  '"Майк Ньюелл"': '"Mike Newell"', '"Марі Окада"': '"Marie Okada"', '"Девід Йєйтс"': '"David Yights"',
                  '"Мімі Ледер"': '"Mimi Leder"', '"Нік Райделл"': '"Nick Rydell"'}

main_roles_dict = {'"Джонні Флінн"': '"Johnny Flynn"', '"Ерік Робертс"': '"Eric Roberts"',
                   '"Лу Ферріньо"': '"Le Ferrigno"', '"Пьотр Адамчик"': '"Piotr Adamchik"',
                   '"Алан Марриотт"': '"Alan Marriot"', '"Тоні Люн Чу Вай"': '"Tony Lun Chu Wai"',
                   '"Jim Morrison"': '"Jim Morrison"', '"Самара Вівінг"': '"Samara Viving"',
                   '"Dev Patel"': '"DEV Patel"', '"Мішель Блан"': '"Michelle Blanc"',
                   '"Марчелло Мастроянні"': '"Marcello Mastrovan"',
                   '"Ведучий - Джеремі Айронс"': '"Leader - Jeremy Ayrons"', '"Ліз Дьєппа"': '"Liz Dieppa"',
                   '"Джої Кінг"': '"Joey King"', '"Том Шилінґ"': '"Tom Shilling"', '"Марія Каллас"': '"Maria Callas"',
                   '"Тео Ю"': '"TEU YU"', '"Самара Уївінґ"': '"Samara Wibing"', '"Ребекка Ромейн"': '"Rebecca Romein"',
                   '"Джон Проктор - Річард Армітідж"': '"John Proctor - Richard Armitidge"',
                   '"Шейлін Вудлі"': '"Shailin Woodley"', '"Расмус Ботофт"': '"Rasmus Botoft"',
                   '"Антоніо Лопес"': '"Antonio Lopez"', '"Ізабель Юппер': '"Isabel Upper',
                   '"Деніел Редкліфф"': '"Deniel Redcliffe"', '"Емі Адамс"': '"Amy Adams"',
                   '"Девід Хеммінгс"': '"David Hemmings"', '"Валері Донзеллі"': '"Valery Donzelli"',
                   '"Антон Святослав Грін"': '"Anton Svyatoslav Green"', '"Вера Фарміга"': '"Vera Farming"',
                   '"Ендрю Гарфілд"': '"Andrew Garfield"', '"Кая Скоделарио"': '"Kaya Skodelary"',
                   '"Енгаурі Райс"': '"Engauri Rice"', '"Ізабелла Гомес"': '"Isabella Gomez"',
                   '"Кері Рассел"': '"Kerie Russell"', '"Лі Сон-хв"': '"Lee Son-min"',
                   '"Франко Интерленги"': '"Franco Interleng"', '"Джордж Костурос"': '"George Kosturos"',
                   '"Дакота Ґорман"': '"Dakota Gorman"', '"Віктор Григор\'єв"': '"Victor Grigoriev"',
                   '"Тім Рот"': '"Tim Roth"', '"Роберт Редфорд"': 'Robert Redford', '"Обрі Плаза"': '"Obi Plaza"',
                   '"Дакота Джонсон"': '"Dakota Johnson"',
                   '"Люк Тредевей Селін Джонс Деніел Іґан"': '"Luke Trendevaya Selen Jones Daniel Igan"',
                   '"Юріа Нара"': '"Suria Nara"', '"Кленсі Браун"': '"Clenes Brown"',
                   '"Джордж МакКей"': '"George Mackay"', '"Rosanna Arquette"': '"Rosan Archueet"',
                   '"Еббі Джейкобсон"': '"Ebby Jacobson"', '"Степан Девонін"': '"Stepan Devonin"',
                   '"Ева Аче"': '"Eva Ace"', '"Tom Hardy"': '"Tom Hardy"', '"Дайан Кітон"': '"Diane Coton"',
                   '"Джейд Чиноует"': '"Jade Chinowet"', '"Маггі К’ю"': '"Maggie KJ"',
                   '"Джеймі Нью - Джон МакКрей"': '"Jamie New John Macray"', '"Ділан О\'Брайен"': '"Dylan O\'Brien"',
                   '"Ніколь Мун\'ос"': '"Nicole Mun\'os"', '"Ян Яньдо"': '"Jan Yano"',
                   '"Логан Маршалл-Грін"': '"Logan Marshall Green"', '"Джеймі Дорнан"': '"Jamie Dorinna"',
                   '"Меттью МакКонахі "': '"Matthew McConhahi"', '"Джерард Батлер"': '"Gerard Butler"',
                   '"Емілія Кларк"': '"Emilia Clark"',
                   '"Сет Ґрін Брекін Меєр Бренда Сонґ Маколей Калкін Клер Грант Кедар Вільямс-Стірлінґ Рейчел Блум"': '"SET Grin Brecin Meir Brenda Sun Makoleka Kalkin Claire Grant Chard Williams-Stirling Rachel Bloom"',
                   '"Дензел Вашингтон"': '"Denzel Washington"', '"Люк Брейсі"': '"Luke Bress"',
                   '"Ях\'я Магайні"': '"Jahia Magain"', '"Криштоф Гадек"': '"KRIST GADEK"',
                   '"Христина Хендрікс"': '"Christina Hendrix"', '"Ноель Фішер"': '"Noel Fischer"',
                   '"Чарлі Палмер Ротвелл"': '"Charlie Palmer Rottwell"', '"Клотільда Куро"': '"Klotilda Kuro"',
                   '"Наталі Бай"': '"Natalie Bai"', '"Майкл Пітт"': '"Michael Pitt"',
                   '"Емілі Ратаковскі"': '"Emily Ratakovsky"', '"Кіану Рівз "': '"Kiana Reeves"',
                   '"Гіларі Свенк"': '"Gilara Svenko"', '"Emily Blunt"': '"Emily Blunt"',
                   '"Емілія Шуле"': '"Emilia Shuli"', '"Руперт Фарлі "': '"Rupert Farnel"',
                   '"Еллісон Дженні Міла Куніс Нора Люм Джиммі Сімпсон Джульєтт Льюїс Меттью Модайн Еллен Баркін Кріс Лоуелл Кліфтон Коллінз-мол. Реджина Голл"': '"Ellison Jenny Mila Kunis Nora Jimmy Simpson Juliet Lewis Matthew Moden Ellen Barkin Chris Lowell Clifton Collins-ml. Regina Gall',
                   '"Алоїс Агаесс-Майї"': '"Alois AGAESS-Maya"', '"Сон Кан-Хо"': '"Cana Ho Son"',
                   '"Ренді Шеллі"': '"Randy Shelly"', '"Енн Гетевей"': '"Ann Gateway"',
                   '"Keith Flint"': '"Keyth Flint"', '"Dave Johns"': '"Give yogens"',
                   '"Сара Наточенні"': '"Sarah Todden"', '"Лейк Белл"': 'Lake Bell', '"Джонні Депп"': '"Johnny Depp"',
                   '"Наталі Дормер"': '"Natalie Dommer"', '"Сем Бейн"': '"Sam Bain"', '"Кевін Харт"': '"Kevin Hart"',
                   '"Роберт Де Ніро"': '"Robert de Niro"', '"Гунда"': '"GUNA"', '"Дастін Гоффман"': '"Dustin Goffman"',
                   '"Малін Акерман"': '"Malin Ackerman"', '"Олександра Естін"': '"Alexander Estin"',
                   '"Девід Духовни"': '"David Duhovniy"', '"Коко Джек Гілліс"': '"Coco Jack Gillis"',
                   '"Леонардо Ді Капріо"': '"Leonardo DiCaprio"', '"Алісія Вікандер"': '"Alicia Vicander"',
                   '"Timothée Hal Chalamet"': '"Timothée Hal Chalamet"', '"Фібі Воллер-Брідж"': '"Fibi Voller Bridge"',
                   '"Хлоя Морец"': '"Chloe Moretz"', '"Джессі Айзенберг"': '"Jesse Eisenberg"',
                   '"Дженніфер Лоуренс"': '"Jennifer Lawrence"', '"Генрі Кавілл"': '"Henry Caville"',
                   '"Лінда Гемілтон"': '"Linda Hemilton"', '"Ґері Олдмен': '"Gary Oldmen',
                   '"Ремі Малек"': '"Remy Malek"', '"Мішель Ларок"': '"Michel Larco"',
                   '"Бріттані Ешворт"': 'Brittany Ashworth', '"Матьє Амальрік"': '"Matie Amalrik"',
                   '"Джуді Грір"': '"Judy Greer"', '"Тарон Еджертон"': '"Taron Ecerton"', '"Емма Стоун': '"Emma Stone',
                   '"Фіона Гордон"': '"Fiona Gordon"', '"Омар Чапарро"': '"Omar Chaparto"',
                   '"Мартін Фрімен"': '"Martin Freeman"', '"Крістен Белл"': '"Kristen Bell"',
                   '"Дженніфер Еністон"': '"Jennifer Aniston"', '"Енн Хетеуей"': '"Ann Heteway"',
                   '"Роман Борисевич"': '"Roman Borisevich"', '"Елізабет Мосс"': '"Elizabeth Moss"',
                   '"Бен О’Тул"': '"Ben O\'Tool"', '"Рейчел МакАдамс"': '"Rachel Makadams"',
                   '"Емілі Блант"': '"Emily Blunt"', '"Двейн Джонсон"': '"Dwin Johnson"', '"Том Хенкс"': '"Tom Hanks"',
                   '"Максим Рой"': '"Maxim Roy"',
                   '"Timothée Chalamet"': '"Timothee Chalamet"', '"Анджей Хира"': '"Angia Chira"',
                   '"Ґаель Ґарсія Берналь"': '"Gael Garcia Bernal"', '"Кейко Екодзава"': '"Keyko Ekodzawa"',
                   '"Еббі Лі Кершоу"': '"Abby Lee Cures"',
                   '"Імоджен Путс"': '"Imogene Puts"', '"Сет Роген"': '"SET Rogen"',
                   '"Наталі Портман"': '"Natalie Portman"', '"Мадлен Брюер"': '"Madeleine Brewer"',
                   '"Віра Фарміґа"': '"Vira Farmga"',
                   '"Рубі Роуз"': '"Rouge Rose"', '"Хав\'єр Боте"': '"Javier Botty"', '"Гайя Вайс"': '"Gaya Weiss"',
                   '"Джессіка Рот"': '"Jessica Roth"', '"Маккензі Девіс"': '"McKenzie Davis"',
                   '"Кріс Пратт"': '"Chris Pratt"', '"Кеннет Брана"': '"Kenneth Brana"',
                   '"Хлоя Ґрейс Морець"': '"Chloe Grace Morets', '"Анна Марія Мюе"': '"Anna Mary Muy"',
                   '"Anthony Ramos"': '"Anthony Ramos"', '"Кері Малліган"': '"Cary Malligan"',
                   '"Венсан Ліндон"': 'Vensan Lindon "', '"Вірджині Ефіра"': '"Virginia ester"',
                   '"Кеті Голмс"': '"Katie Golmes"', '"Меґан Фокс"': '"Magan Fox"', '"Джоді Фостер"': '"Jody Foster"',
                   '"Марк Волберг"': '"Mark Volberg"', '"Юрій Кулініч"': '"Yuri Cookinich"',
                   '"Генрі Голдінг"': '"Henry Golding"', '"Іоанна Куліг"': '"John Kulig"',
                   '"Еммі Россам"': '"Emmi Rossam"', '"Джозефіна Ленгфорд"': '"Josephin Langford"',
                   '"Логан Міллер"': '"Logan Miller"',
                   '"Сіньє Ірслінґер Макс Губахер Тіль Швайґер Юрґен Фоґель Джасмін Джерат Моріц Бекерлінг Інка Фрідріх Денніс Моен"': '"Sonyne Islinger"',
                   '"Маґдалена Колеснік"': '"Magdalen Kolesnik"', '"Флоріан Давід Фіц"': '"Florian David Fit"',
                   '"Том Герхардт"': '"Tom Gerhardt"', '"Кірбі Гавелл-Баптіст"': '"Kirby Gavel Baptist"',
                   '"Фредді Меркьюрі"': '"Freddy Mercury"', '"Зак Ґаліфіанакіс"': '"Zac Galiefanakis"',
                   '"Ніна Добрев"': '"Nina Dobrev"', '"Френк Грілло"': '"Frank Grillo"',
                   '"Марі Блокхус"': '"Marie Blockus"',
                   '"Маґуі Браві Луз Шампань Ампаро Еспінола"': '"Magui Brava Lus Champagne Amparo Espinola"',
                   '"Ноа Леві"': '"Noa Levi"', '"Різ Ахмед"': '"MIS Ahmed"', '"Ото Брантевіцс"': '"Moto Bruntevitss"',
                   '"Мелісса Маккарті"': 'Melissa McCarthy', '"Фелісіті Джонс"': '"Felicity Jones"',
                   '"Віллем Дефо"': '"Villem Defo"', '"Вілл Сміт"': '"Will Smith"',
                   '"ГЕНРІ ГОЛДІНГ"': '"Henry Golding"',
                   '"Тетяна Делоне"': '"Tetyana Delon"', '"Катрін Денев"': '"Katrin Denneve"',
                   '"Ділан Гвін"': '"Dylan Gwin"', '"Лів Тайлер"': '"Liv Tyler"',
                   '"Андрій Римарук"': '"Andrew Rimaruk"', '"Хав\'єр Гутьєррес"': '"Javier Gutierrez"',
                   '"Льюїс Тан"': '"Lewis Tang"', '"Ален Шаба"': '"Alen Shaba"', '"Шарліз Терон"': '"Charlize Terron"',
                   '"Тоні Тодд"': '"Tony Todd"', '"Наомі Воттс"': '"Naomi Votts"',
                   '"Крістофер Екклстон"': '"Christopher Eccleston"',
                   '"Сідсе Бабетт Кнудсен"': '"Side Babetht Knudsen"', '"Ніколас Голт"': '"Nicholas Golt"',
                   '"Софія Бутелла"': '"Sofia Boothella"', '"Каллум Малоні"': '"Callum Maloni"',
                   '"Аарон Пол"': '"Aaron Paul"', '"Джеймі Белл"': '"Jamie Bell"',
                   '"Серджо Кастеллітто Сабріна Феріллі Антоніо Катанія"': '"Serjo Castellite Sabrina Ferrile Antonio Catania"',
                   '"Сем Клафлін"': '"Sam Claflin"', '"Стів Орам"': '"Steve Oram"',
                   '"Раян Рейнольдс"': '"Rayan Reynolds"', '"Дар\'я Плахтій"': '"Daria Plakhti"',
                   '"Тесса Томпсон"': '"Tessa Thompson"', '"Кірсі Клемонс"': '"Kirse Clemons"',
                   '"Дієго Марадона"': '"Diego Maradona"', '"Річі Меррітт"': '"Richie Merritt"',
                   '"Алек Утгофф"': '"Aleek Uthaff"', '"Шана Керслейк"': '"Shana Kersleyk"',
                   '"Боб Оденкірк"': '"Bob Odenkirk"', '"Джейсон Кларк"': '"Jason Clark"',
                   '"Сільвестр Сталлоне"': 'Sylvester Stallone "', '"Ембер Хьорд"': '"Ember Khour"',
                   '"Еллен Пейдж"': '"Ellen Page"', '"Рейчел Броснаген"': '"Rachel Brosnagen"',
                   '"Ізабела Мерсед"': '"Isabela Merced"', '"Франческа Реале"': '"Francesca Real"',
                   '"Алікс Пуасон"': '"Alix Poison"',
                   '"Том Хіддлстон Марк Гетісс Хедлі Фрайзер Жаклін Боутсвейн Пітер Де Джерсі Альфред Енок Дебора Файндлей Елліот Леві Люсі Осборн Роченда Сандалл"': '"Tom Hiddston Mark Getings Headly Frezer Jacquelin Beatswin Peter De Jersey Alfred ENO Deboro Findley Elliot Levy Lucy Osborn Rochenta Sandall',
                   '"Альбер Дюпонтель"': '"Alber Dupontel"', '"Кетрін Ньютон"': 'Catherine Newton',
                   '"Елізабет Лейл"': '"Elizabeth Leil"', '"Олег Мельничук"': '"Oleg Melnichuk"',
                   '"Юен МакГрегор"': '"Yuen McGregor"', '"Вуді Гаррельсон"': '"Wood Garrellon"',
                   '"Вівіан Лу"': '"Vivian Lou"', '"Каролін Кебекус"': '"Carolyn Kebecus"',
                   '"Ніл Адамс"': '"Nile Adams"', '"Демі Ловато"': '"Demi Lovato"',
                   '"Честер Беннінгтон"': '"Chester Bennington"',
                   '"Лора Фрейзер Еліс Лоу Вінсент Ріган Шон Нопп"': '"Laura Fraser Alice Lowe Vincent Rigan Sean NOPP"',
                   '"Брайан Кренстон"': '"Brian Cranston"', '"Елісон Брі"': '"Alison Brie"',
                   '"Альфред Б\'єрр Ларсен"': 'Alfred Bjer Larsen "', '"Сімон Абкарян"': '"Simon Abkarat"',
                   '"Елайджа Вуд': '"Elajja Wood',
                   '"Домінік Вест Роуз Леслі Роб Брайдон Джемма Чан Берті Карвел Темсін Ґреґ Айзек Гемпстед Райт Бел Паулі"': '"Dominique West Rose Leslie Rob Braday Jemma Chan Bertie Carvel Temsein Greg Iszek Hampstead Wright Bel Pauli"',
                   '"Луі Гаррель"': '"Lui Garrel"', '"Морган Фріман"': 'Morgan Freeman "',
                   '"Марк Стронг Ніколя Уолкер Фібі Фокс Іман Елліотт Люк Норріс Майкл Гулд"': '"Mark Strong Nicolas Walker Fibi Fox Iman Elliott Luke Norris Michael Gould"',
                   '"Ева Куаттроксі"': '"Eva Kuattrox"', '"Кріс Хемсворт"': '"Chris Hamsworth"',
                   '"Saoirse Ronan"': '"Saoirs Ronan"', '"Х\'ю Грант"': '"Hugh Grant"',
                   '"Сільвія Хукс"': '"Silvia Hux"', '"Кейт Бланшетт"': '"Kate Blanchett"',
                   '"Чень Пейси"': '"Chen Pays"', '"Крістіан Бейл"': '"Christian Bale"', '""': '""',
                   '"Жан Рено"': '"Jean Reno"', '"Кіра Найтлі"': '"Kira Knightly"',
                   '"Abbie Cornish"': '"Abbie Chornosh"', '"Кумейл Нанджиані"': 'Nanjian Komeil "',
                   '"Марк-Андре Гронден"': '"Mark-Andre Grønden"', '"Майя Ерскін"': '"Maya Erskin"',
                   '"Валентина Лодовіні"': '"Valentine Lodon"', '"Хеннінг Баум"': '"Henning Baum"',
                   '"Брі Ларсон"': '"Brie Larson"', '"Семадж Александр Каннінгем"': '"Semaj Alexander Cunningham"',
                   '"Марі-Жозе Кроз"': '"Marie-Jose Kroz"', '"Софія Лілліс"': '"Sofia Lillis"',
                   '"Ліндсі Морган"': 'Lindsi Morgan "', '"Leonardo DiCaprio"': '"Leonardo Dicaprio"',
                   '"Елізабет Олсен"': '"Elizabeth Olsen"', '"Гарві Кейтель"': '"Garbi Kitel"',
                   '"Таісса Фарміга"': '"Tissa Farming"', '"Г\'юґо Бекер"': '"Gügo Becker"',
                   '"Кад Мерад"': '"Cad Merad"', '"Юрґен Фоґель"': '"Yurgen Fogel"', '"Омар Сі"': '"Omar SI"',
                   '"Джуд Лоу"': '"Juda Lowe"', '"Нілам Фарук"': '"Nile Faruk"',
                   '"Кайлер Чарльз Бек"': '"Kairer Charles Beck"', '"Андреа Бескон"': '"Andrea Beskon"',
                   '"Джим Керрі"': '"Jim Carrey"',
                   '"Вірджині Ефіра Альбер Дюпонтель Жаккі Берруайе Бастьєн Уґетто Мішель В\'юєрмоз Грегуар Людіг Давід Марсе Булі Ланнер Террі Ґілліам"': '"Virginia Etir Alber Dupotel Jacqui Berroye Bostto Bostto Michel Vyermosis Gregory Lyudig David Mars Bullie Lanner Terry Gilliam"',
                   '"Еліас ЕмБарек"': '"Elias Embark"', '"Хоакін Рафаель Фенікс"': '"Hoaquin Rafael Phoenix"',
                   '"Ліам Нісон"': '"Liam Nison"', '"Ґаль Ґадот"': '"Gate Gadot"',
                   '"Ельза Зільберштейн"': '"Elsa Zilberstein"', '"Еллі Харбоу"': '"Ely Harbow"',
                   '"Ідріс Ельба"': '"Irris Elba"', '"Ульріх Томсен"': '"Ulrich Tomsen"',
                   '"Джессіка Маклеод"': '"Jessica Maklideo', '"Хіро Файнс-Тіффін"': '"Hiro Fyns Tiffin"',
                   '"Х\'ю Джекман"': '"Hugh Jackman"', '"Росс Лінч"': '"Ross Lynch"',
                   '"Зої Маргарет Коллетті"': '"Zoe Margaret Collette"', '"Роксана Лупу"': '"Roxana Lupu"',
                   '"Райлі Кіо"': '"Riley Kio"', '"Кьяра Мастроянні"': '"Kyara Mastrovan"',
                   '"Джемма Артертон"': '"Jemma Artererton"', '"Єва Меландер"': '"Eva Mellander"',
                   '"Ангела Ґрегович"': '"Angela Gregovich"', '"Nirvana"': 'nirvana', '"Ґері Олдман"': '"Gary Oldman"',
                   '"Лоік Гузер"': '"Loik Guzer"', '"Беккі Джи"': '"Becky Gee"', '"Алекс Дрейпер"': '"Alex Dareyper"',
                   '"Амандла Стенберг"': '"Ammanl Stanberg"', '"Девід Теннант"': '"David Tennant"',
                   '"Гаррісон Форд"': '"Harrison Ford"', '"Мадс Міккельсен"': '"Mads Mikkelsen"',
                   '"Джош Лукас"': '"Josh Lukas"', '"Деніел Крейґ"': '"Deniel Craig"', '"ВІНС ВОН"': '"Vince Won"',
                   '"Лінда Карделліні"': '"Linda Cardellini"', '"Сабріна Керн"': '"Sabrin Corn"',
                   '"Клайв Оуен"': '"Klive Owen"', '"Майкл Б. Джордан"': '"Michael B. Jordan"',
                   '"Джош Цуккерман"': '"Josh Zukkerman"', '"Лоліта Шамма"': '"Lolita Shamma"',
                   '"Том Харді"': '"Tom Hardy"', '"Ема Хорват"': '"Ema Croat"', '"Чжан Вей"': '"Zhang Wei"',
                   '"Джемі Орам"': '"Jami Oam"', '"Раян Пінкстон"': '"Rayan Pinkston"', '"Кен Джонг"': '"Ken Jong"',
                   '"Дженніфер Лопес"': '"Jennifer Lopez"', '"Энтоні Майкл Холл"': '"Eton Michael Hall"',
                   '"Метью Модін"': '"Matthew Modin"', '"Люсі Лоулесс"': '"Lucy Lawess"',
                   '"Гарі Олдман"': '"Gary Oldman"', '"Кірк Хемметт"': '"Kirk Hemmett"',
                   '"Vera Farmiga"': '"Vera Farming"', '"Семюел Л. Джексон"': '"Samuel L. Jackson"',
                   '"Адам Драйвер"': '"Adam Driver"', '"Крістофер Ебботт"': '"Christopher Ebbott"',
                   '"Ґері Олдмен"': '"Gary Oldman"', '"Уілл Вернік  Холланд Роден"': '"Will Vernick Holland Roden"',
                   '"Райан Карнс"': '"Ryan Karns"', '"Марлен Лозе"': '"Marlen Lause"', '"Simu Liu"': '"Sam Liu"',
                   '"Коул Спроус"': '"Cole Trace"', '"Деніел Кеш"': '"Deniel Cache"', '"LeBron James"': '"LeBron Yams"',
                   '"Соломон Ґордон"': 'Solomon Gordon', '"Ніколь Кідман"': '"Nicole Kidman"',
                   '"Роланд Мюллер"': '"Roland Muller"', '"Jason Statham"': '"Jason articles"',
                   '"Рейф Сполл"': '"Rafa Spoon"', '"Viggo Mortensen"': '"Vigo Mortensen"',
                   '"Меггі Кью"': '"Maggie Kew"',
                   '"Жан Дюжарден': '"Jean Dugarden', '"Ванесса Кірбі"': '"Vanessa Kirby"',
                   '"Орландо Блум"': 'Orlando Bloom', '"Томас Джейн"': '"Thomas Jane"',
                   '"Вільям Болдуін"': '"William Baldwin"', '"Софі Тернер"': '"Sophie Turner"',
                   '"Меґґі К’ю"': '"Meggy Kew"', '"Олівія Манн"': '"Olivia Mann"',
                   '"Саммер Фонтана"': '"Fountain Summer"', '"Розамунд Пайк"': '"Rosamund Pike"',
                   '"Івонн Страховські"': '"Ivon Insurance"', '"Liam Neeson"': '"Liam Non"',
                   '"Ніколас Кейдж"': '"Nicholas Cage"', '"Мел Гібсон"': '"Mel Gibson"',
                   '"Анджеліна Джолі"': '"Angelina Jolie"', '"Франсуа Клюзе"': '"Francois Klyuse"',
                   '"Rose Byrne"': '"Rose storm"', '"Мішель Родрігес"': '"Michelle Rodriguez"',
                   '"Шайа ЛаБаф"': '"Shaia Labaf"', '"Сергій Полунін"': '"Sergey Polonin"',
                   '"Гійом Кане"': '"Games Kane"', '"Бенісіо дель Торо"': '"Benio del Toro"',
                   '"Matt Damon"': '"Mat Damon"', '"Бріджитт Лін"': '"Bridgett Lin"',
                   '"Райан Рейнольдс"': '"Ryan Reynolds"', '"Наташа Генстрідж"': '"Natasha Henchtridge"',
                   '"Ерін Моріарті"': '"Erin Moriarty"', '"Бен О\'Тул"': '"Ben O\'Tool"', '"Рафф Лоу"': '"Raffo Low"',
                   '"Чарлі Шин"': '"Charlie Sheen"', '"Леді Гага"': '"Lady Gaga"', '"Дейзі Рідлі"': '"Daisy rare"',
                   '"Петтон Освальт"': '"Petton Oswalt"', '"Денніс Куейд"': 'Dennis Kuayd "', '"Ед Кейр"': '"Ed Keir"',
                   '"Кана Кіта"': '"Kan Kita"', '"Нік Робінсон"': '"Nick Robinson"', '"Девід Харбор"': '"David Harbor"',
                   '"Дензел Вашинґтон"': '"Denzel Washington"', '"Хейлі Стайнфелд"': '"Haley Stinfeld"',
                   '"Елісон Уолкер"': '"Alison Walker"', '"Кая Скоделаріо"': '"Kaya Skodelio"',
                   '"Марго Роббі"': '"Mro Robbie"', '"СТІВЕН ЛЕНҐ"': '"Stephen Leng"',
                   '"Том Уілкінсон"': '"Tom Wilkinson"', '"Карен Гіллан"': '"Karen Gillan"',
                   '"Терон Еджертон"': '"Terron Ecerton"', '"Ромен Дюріс"': '"Romain Duris"',
                   '"Раян Гузман"': '"Rayan Gumman"', '"Ізабель Юппер"': '"Isabel Upper"',
                   '"Тобі Джонс"': '"Tobi Jones"', '"Кассандра Маграт"': '"Cassandra Magat"',
                   '"Джейкоб Трембле': '"Jacob Tremble', '"П\'єр Ніне "': '"Pierre Nine"',
                   '"Колін Фаррелл"': '"Colin Farrell"', '"Катрін Лідстоун"': '"Katrin Lidstone"',
                   '"Джек Ніколсон"': '"Jack Nikolson"', '"Енн Гетевей': '"Anne Heteway',
                   '"Тільда Свінтон"': '"Tilde Senton"', '"Ірен Жакоб"': '"Irene Jacob"', '"Даг Джонс"': '"Dag Jones"',
                   '"Венсан Кассель"': '"Vensan Kassel"', '"Джеймс Макевой"': '"James Makeva"',
                   '"Кіт Гарінґтон"': '"Kit Garington"', '"Макіта Самба"': '"Makita Samba"',
                   '"Джеймі Фокс"': '"Jamie Fox"', '"Лілі Джеймс"': '"Lily James"', '"Хейлі Бішоп"': '"Hale Bishop"',
                   '"Бен Діскін"': '"Ben Dyskin"', '"Стівен Рут"': '"Stephen Ruth"',
                   '"Ед Скрейн"': '"Ed Scrin"', '"Демі Мур"': '"Demi Moore"', '"Коді Сміт-МакФі"': '"Smith Macfi Cody"',
                   '"Міранда Тапселл"': 'Miranda Tapsell', '"Біллі Айліш"': '"Billy Aylish"',
                   '"Gemma Chan"': '"Gema Chan"', '"Манака Івамі"': '"Iwami Manaca"',
                   '"Дуейн Джонсон"': '"Duyn Johnson"', '"Магнус Креппер"': '"Magnus crepe"',
                   '"Том Холланд"': '"Tom Holland"', '"Оскар Айзек"': '"Oscar Isec"',
                   '"МІЛА ЙОВОВИЧ"': '"Mila Yovovich"',
                   '"Тейлор Шиллінг"': '"Taylor Shilling"', '"Леонардо Дікапріо"': '"Leonardo DiCaprio"',
                   '"Джеффрі Дін Морґан"': '"Jeffrey Dean Morgan"', '"Ель Фаннінг"': '"El Fanning"',
                   '"МакКенна Грейс"': '"McKenna Grace"', '"Роберт Дауні мл."': '"Robert Downy ml."',
                   '"Джек Вайтхолл"': '"Jack Whiteholl"', '"Сільві Моро"': '"Silvi Moro"',
                   '"Пітер Дінклейдж"': '"Peter Dinklej"', '"Ніколас Хоуп"': '"Nicholas Hope"',
                   '"Кей Джей Апа"': '"Kay Jay APA"',
                   '"Френсіс Хеншелл - Джеймс Корден"': '"Francis Henshell - James Corden"',
                   '"Сем Уортінгтон"': '"Sam Worthington"', '"КЕВІН КОСТНЕР"': '"Kevin Kostner"', '"Ху Ге"': '"Hu Ge"',
                   '"Гаспар Ульєль"': '"Gaspar Ulel"', '"Морена Баккарін"': '"Morena baccarin"',
                   '"Бенедикт Камбербетч"': '"Benedict Camberbetch"', '"Леброн Джеймс"': '"LeBron James"',
                   '"Дженніфер Гарнер"': '"Jennifer Garner"', '"Том Голланд"': '"Tom Golland"',
                   '"Брайс Даллас Ховард"': '"Bryce Dallas Hovard"', '"Уілл Паттон"': '"Will Patton"',
                   '"Адель Енель"': '"Adele Enerel"', '"Дакота Джонсон': '"Dakota Johnson',
                   '"Рене Зеллвеґер"': '"Rene Zellveger"', '"Люк Еванс"': '"Luke Evans"',
                   '"Роберто Беніньї"': '"Roberto Beninyi"', '"Лів Шрайбер"': '"Liv Shrayber"',
                   '"Яннік Шуманн"': '"Yannik Schumann"', '"Марен Еґґерт"': '"Maren Eggert"',
                   '"Крістіан Клав’є"': '"Christian Clavie"', '"Тейлор Кітч"': '"Taylor Kitch"',
                   '"Емма Стоун"': '"Emma Stone"', '"Моніка Беллуччі"': '"Monica Bellucci"',
                   '"Брентон Туейтес"': '"Brenton Tuites"', '"Арвед Фрізе"': '"Arved Freise"',
                   '"Джо Манґаньєлло"': '"Joe Manganyello"', '"Джекі Чан"': '"Jackie Chan"',
                   '"Сер Роберт Чилтерн - Натаніель Паркер"': '"Sir Robert Chiltern - Nathaniel Parker"',
                   '"Кіану Рівз"': '"Kiana Reeves"', '"Анджеліна Джолі': '"Angelina Jolie',
                   '"Бенжамін Лаверн"': '"Benjamin Lavern"', '"Бен Платт"': '"Ben Platts"',
                   '"Frances McDormand"': '"Frantse Mzdormand"', '"Емілі Бічем"': '"Emily Beach"',
                   '"Зоріца Нушева"': '"Zoritsa Nosheva"', '"Скарлетт Йоганссон"': '"Scarlett Yegansson"',
                   '"Брюс Вілліс"': '"Bruce Willis"', '"Джейсон Айзекс"': '"Jason Iszex"',
                   '"Сальвадор Далі"': '"Salvador further"', '"Аннабелль Волліс"': '"Annabell Vollis"',
                   '"Ешлі Боеттчер"': '"Ashley Bayetycher"', '"Лора Фрейзер"': '"Laura Fraser"',
                   '"Ханна Бодро"': '"Hannah Botro"', '"Джульєтта"': '"Juliet"',
                   '"Келлі Марі Тран"': '"Kelly Mary Tran"',
                   '"Самара Вівінґ"': '"Samara Viving"', '"Hugh Jackman"': '"Hug Yazkman"',
                   '"Хару Курокі"': '"Haru Kuroki"',
                   '"Аліс Гі Річард Абель Марк Абрахам Стефані Еллейн Джилліан Армстронг Джон Бейлі Кері Бошан Лейк Белл"': '"Alice Gi Richard Mark Abraham Stephanie Ellain Gillian Armstrong John Bailey Kerie Boshan Lake Bell"',
                   '"Жан Дюжарден"': '"Jean Dugarden"', '"Джессіка Честейн"': '"Jessica Chestine"',
                   '"Сьюкі Уотерхаус"': '"Sewy Waterhouse"', '"Уілльям Лебхіл"': '"William Lebchil"',
                   '"Адевале Акінойє-Агбаже"': '"Adeval Akinoey-Agbage"',
                   '"Фолькер Міхаловскі"': '"Folker Michalovski"', '"Елайджа Вуд"': '"Elijja Wood"',
                   '"Ейса Гонсалес"': '"Eis Gonzalez"', '"Кейсі Аффлек"': '"Casey Afflek"',
                   '"Райан Гузман"': '"Ryan Gumman"', '"Дайана Кітон"': '"Dayana Coton"',
                   '"Мелісса Джордж"': '"Melissa George"', '"Алан Тьюдік"': '"Alan Tyudik"',
                   '"Джейк Джилленхол"': '"Jake Gilllene"', '"Margot Robbie"': '"Robbie Margot"',
                   '"Крістіна Річчі Джон Кьюсак Брендан Флетчер Олівер Райс"': '"Christina Ricci John Keusak Brendan Fletcher Oliver Rice"',
                   '"Армі Хаммер"': '"Army Hummer"', '"Джейсон Сімпсон"': '"Jason Simpson"',
                   '"Луїз Лабек"': '"Luhe Labek"', '"Румі Хирагі"': '"Rumy Chirhai"',
                   '"Нільс Шнайдер"': '"Nils Schneider"', '"Пол Радд"': '"Paul Rudd"',
                   '"Сальваторе Еспозіто"': '"Salvatore Esposito"', '"Алан Каммінг"': '"Alan Camping"',
                   '"Пе Ду-на"': '"PE do-on"', '"Белла Торн"': '"Bella Torn"', '"Фабріс Лукіні"': '"Fabris Lukini"',
                   '"Карлі Поуп"': '"Carly POUP"', '"Бокім Вудбайн"': 'Bokim Wedbane',
                   '"Леонід Барац"': '"Leonid Baraz"',
                   '"Хьюго Уівінг"': '"Hugo Whivding"', '"Alexander Skarsgård"': '"Alexander Skarsgård"',
                   '"Міла Куніс"': '"Mila Kunis"', '"Імелда Стонтон"': '"Imlet Stanton"',
                   '"Пернілла Аугуст"': 'Pernilla August', '"Стеллан Скашгорд"': '"Stellan Skashgorod"',
                   '"Тоні Коллетт"': '"Tony Collette"', '"Райан Бенсетті"': '"Ryan benesetti"',
                   '"Ділан О’Браєн"': '"Dylan O\'Bell"', '"Хелен Кревел"': '"Helen Craple"',
                   '"Роберт Казінськи"': 'Robert Kazinski', '"Алекс Полідорі"': '"Alex Polidor',
                   '"Александра Даддаріо"': '"Alexander Daddario"', '"Марк Волберґ"': '"Mark Volberg"',
                   '"Ітан Хоук"': '"Ethan Hawk"', '"Даніель Брюль"': '"Daniel Brül"',
                   '"Г\'ю Джекман"': '"H\'u Geckman"',
                   '"Анна Елізабет Анна Марі Доббінс Віктор Рівера"': '"Anna Elizabeth"',
                   '"Джеффрі Дін Морган"': '"Jeffrey Dean Morgan"', '"Метт Деймон"': "Matt Damon '",
                   '"Зої Салдана"': '"Zoe Saldana"', '"Ісаак Лобе-Лебель"': '"Isaac Lobe Lebel"',
                   '"Вінсент Д\'онофріо"': '"Vincent d\'ionfrio"', '"Том Генкс"': '"Tom Genks"',
                   '"Конор Беррі Шон Коннор Мінгус Джонстон"': '"Konor Berry Sean"',
                   '"Жанель Моне"': '"Jenel Monet"', '"Гвендолін Крісті"': '"Gwendolin Christie"',
                   '"Софі Тьорнер"': '"Sophie Thickerner"', '"Фредеріке Бехт"': '"Frederike Becht"',
                   '"Тео Фернандез"': '"Fernandez Fernandez"', '"Аманда Сейфрід"': '"Amanda Seyfrid"',
                   '"Джеймс МакЕвой"': '"James Makeva"', '"Франсуа Сівіль"': '"Francois Sivil"',
                   '"Елізабет Дебики"': '"Elizabeth Debiki"', '"Стівен Йон"': '"Stephen Yon"',
                   '"Керрі Кун"': '"Kerry Kun"', '"Колін Ферт"': '"Colin Fert"', '"Дейв Батіста"': '"Dave Batista"',
                   '"Кая Кіхара"': '"Kaya Kichara"', '"Пенелопа Крус"': '"Penelope Cruz"',
                   '"Ванесса Грасс"': '"Vanessa Grass"', '"Ахтем Сейтаблаєв"': '"Akhtem Seytablahav"',
                   '"КЕЙТ ВІНСЛЕТ"': '"Kate Vincilet"', '"Tom Hanks"': '"Tom Hanks"', '"Том Круз"': '"Tom Cruz"',
                   '"Шан Брук"': '"Shang Brook"', '"Махершала Алі"': '"Mahrzala Ali"',
                   '"Саллі Хокінс"': '"Sally Hawkins"', '"Майкл Хербіг"': '"Michael Herbig"',
                   '"Джеймс Вілкс"': '"James Wilks"', '"Роуз Бірн"': '"Rose Byrne"',
                   '"Торбьорн Харр"': 'Torbjorn Harr "', '"Адам Коупленд"': '"Adam Coplind"',
                   '"Daisy Ridley"': '"Daisi rare"', '"Клінт Іствуд"': '"Clint Eastwood"',
                   '"Ізабела Монер"': '"Isabela MOHER"', '"Аня Тейлор-Джой"': '"Anya Taylor Joy"',
                   '"Скарлетт Йоганссон': '"Scarlett Yegansson', '"Сюн Огурі"': '"Sun Ogar"',
                   '"Марина Д’яконенко"': '"Marina Diakonenko"', '"Бред Пітт"': '"Brad Pitt"',
                   '"Ірма Вітовська-Ванца"': '"Irma Vitovskaya Wanza"', '"Деніза Юхос"': '"Deniza Yukos"',
                   '"Чекі Каріо"': '"Cheki Cario"', '"Нумі Рапас"': '"Rapas Numo"', '"Джуді Денч"': '"Judy Dench"',
                   '"Джош Бролін"': '"Josh Broln"', '"Саймон Раселл Біл"': '"Simon Rasell Bil"',
                   '"Ліам Галлахер"': '"Liam Gallagher"', '"Бояна Новакович"': '"Boyan Novakovich"',
                   '"Маріт Андреассен"': '"Marit Andreasen"', '"Венсан Лакост"': '"Vensan Lacost"',
                   '"Паула Петтон"': '"Paula Petton"', '"Ryan Reynolds"': '"Ryan Reynolds"',
                   '"Бен Вішоу"': '"Ben Wiched"', '"Октавія Спенсер"': '"Octavia Spencer"',
                   '"Меґґі Ґрейс"': 'Meggy Grace', '"Райан Ніколлз"': '"Ryan Nicolls"',
                   '"Крісті Бурк"': '"Christie Burk"', '"Пол Волтер Гаузер"': '"Paul Volter Gauser"',
                   '"Костянтин Мохнач та інші"': '"Constantine Mohnach and others"',
                   '"Міллі Боббі Браун"': '"Millie Bobby Brown"', '"Марґо Роббі"': '"Margo Robbie"',
                   '"Бруно Ґанц Йоханнес Кріш Хаймон Марія Буттінґер Герті Драссль Кароліна Ейхгорн Роберт Сіталер"': '"Bruno Ganz Johannes Chrish Hamon Maria Butinter Herty Drace Carolina Eichororn Robert Sitalal',
                   '"Алек Болдуін"': '"Alec Baldwin"', '"Роберт Дауні мол."': '"Robert Downy mol."',
                   '"Коді Сміт-МакФі': '"Smith McFee Cody', '"Габріель Бейтман"': '"Gabriel Baitman"',
                   '"Джісу"': '"JISU"', '"Двейн Джонсон': '"Dwin Johnson', '"Юель Кіннаман"': '"Yue Kinmanman"',
                   '"У ролях ДЕНІЕЛ КРЕЙҐ"': '"Daniel Craig"', '"Тоні Сервілло"': '"Tony Service"',
                   '"Хейлі Етвелл"': '"Haley Etwell"', '"Кев Адамс"': '"Kev Adams"', '"Ден Стівенс"': '"Dan Stevens"',
                   '"Кокоро Хірасава"': 'Kokoro Hirasawa', '"Ольга Куриленко"': 'Olga Kurylenko',
                   '"Він Дизель"': '"He diesel"', '"Хлоя Грейс Морец"': '"Chloe Grace Mothers"',
                   '"Джейсон Момоа"': '"Jason Momoa"', '"Анна Феріс"': '"Anna Ferris"',
                   '"Scarlett Johansson"': '"Stsarlet Johansson"', '"Марґарет Куоллі"': '"Margaret Kwalli"',
                   '"Мадс Міккельсен Ніколай Лі Кос Ніколас Бро Ґустав Лінд Роланд Мюллер Якоб Ломанн Рікке Луїза Андерссон Альберт Рудбек Ліндгардт"': '"Mads Mikkelsen"',
                   '"Аквафіна "': '"Aquafin"', '"Міккі Рурк"': '"Mickey Rutk"',
                   '"Франческо Ді Наполі"': '"Francesco di Napoli"', '"Angelina Jolie"': '"Angelina yolays"',
                   '"Емі Форсайт"': '"Amy Forsight"', '"Стів Керелл"': '"Steve Kerell"',
                   '"Кассандра Морріс"': '"Cassandra Morris"', '"Джастін Флетчер"': '"Justin Fletcher"',
                   '"Венсан Ельбаз"': '"Veninsan Elbaz"', '"Гай Пірс"': '"Guy Pierce"',
                   '"Кріс Карпентер"': '"Chris Carpenter"', '"Цзі Гуаньлінь"': '"Tsja Guanlin"',
                   '"Марлон Діно"': '"Marlon Dino"', '"Едуард Баер"': '"Edward Bar"', '"Саллі Філд"': '"Sally Field"',
                   '"Майкл Кейн"': '"Michael Kane"',
                   '"Кеті Голмс Джош Лукас Джеррі О’Коннелл Селія Вестон"': '"Katie Golmes Josh Lucas Jerry O\'Connell Silia Weston"',
                   '"Лін Шей"': '"Lin Shey"', '"Ґольшифте Фарахані"': '"Golshifte Farukha"',
                   '"Аннабелль Уолліс"': '"Annabell Wallis"', '"Рейне Сварт"': '"Rayne Svart"',
                   '"Катрін Ґрейс-Розенталь"': '"Katrin Greys-Rosenthal"', '"Каллі Ернандес"': '"Calley Hernandes"',
                   '"Шейла Маккарті"': '"Sheila McCarty"', '"Фамке Янссен': '"Famke Yanssen',
                   '"Меделін Петш"': '"Medelin Pets"', '"Лю Іфей"': '"Liu Ife"', '"Флоренс П\'ю"': '"Florence Pue"',
                   '"Крістен Стюарт"': '"Kristen Stewart"', '"Меттью Белламі"': '"Matthew Bellami"',
                   '"Сара Хайланд"': '"Sarah Hayland"', '"Dwayne Johnson"': '"Two yoginson"',
                   '"Фелікс Моаті"': '"Felix Moati"', '"Джефф Ґолдблюм"': '"Jeff Goldloom"',
                   '"Джульєтт Льюїс"': '"Juliet Lewis"', '"Гезер Ленгенкемп"': '"Gaser Langenkamp"',
                   '"Робін Райт"': '"Robin Rait"', '"Карре Хаген Сіднесс"': '"Carre Hagen Sydness"',
                   '"Tim Roth"': '"Those mouthh"', '"Деметріус Шипп мол."': '"Demetrius hip mol."',
                   '"Vin Diesel"': '"He diesel"', '"Ентоні Рамос"': '"Anthony Ramos"',
                   '"Летиция Дош"': '"Leticia Dosh"',
                   '"Тарек Будалі"': '"Budal Tare"', '"Stephanie Beatriz"': '"Stephanie Beatrice"',
                   '"Джина Карано"': '"Gina Karano"', '"Lewis Tan"': '"Levis Tan"',
                   '"Олівер Мазуччі"': '"Oliver Mazucci"', '"Моріц Бляйбтрой"': 'Moritz Bluebtro',
                   '"Мацей Маковський"': '"Matsay Makovsky"', '"Меріл Стріп"': '"Meril Strip"',
                   '"Крістіан Клав\'є"': '"Christian Clavie"', '"Ребекка Форсайт"': '"Rebecca Forsight"',
                   '"Іванна Сахно"': '"Ivanna Sakhno"', '"Халлдора Гейхадсдоттір"': '"Hulldora Gayhadsdottir"',
                   '"Закарі Лівай"': '"Zakari Livay"', '"Франц Роговський"': '"Franz Rogovsky"',
                   '"Рубі Барнхілл"': '"Ruby Barnchill"', '"Серінда Свон"': '"Serinda Swan"',
                   '"Ґілліан Джейкобс"': '"Gillian Jacobs"', '"Іван Атталь"': '"Ivan Attal"',
                   '"Олександра Ламі"': '"Alexander Lami"', '"Джим Геффіган"': '"Jim Geffigan"',
                   '"Чарлі Ханнем"': '"Charlie Hannem"', '"Ніколай Костер-Вальдау"': '"Nikolay Koster-Waldau"',
                   '"Люпіта Ніонго"': '"Lupita Niego"', '"Брюс Дікінсон"': '"Bruce Dickinson"',
                   '"Фамке Янссен"': '"Famke Yansens"', '"Нора Арнезедер"': '"Nora Arnezer"',
                   '"Іван Реон"': '"Ivan Reon"', '"Єва Грін"': '"Eva Green"', '"Монік Рокман"': '"Monique Rockman"',
                   '"Джуліанна Мур"': '"Julian Moore"', '"Сара-Софи Бусснина"': '"Sara-Sofi Bushsnina"',
                   '"Крістал Рід"': '"Crystal Reed"', '"Катя Паскар"': '"Katya Pascar"',
                   '"Скарлетт Йоханссон"': '"Scarlett Johansson"', '"Селін Ронте"': '"Celine Rhone"',
                   '"Джейсон Стейтем"': '"Jason Stat', '"Ліна Кудрі"': '"Lina Kudry"',
                   '"Елізабет Бенкс"': '"Elizabeth Benx"', '"Ізабель Мей"': '"Izabel Mei"',
                   '"Ребекка Фергюсон"': '"Rebecca Ferguson"', '"Жослін ДеБоер"': '"Julie Deuber"',
                   '"Кейт Вінслет"': '"Kate Vincilet', '"Норма Бастідас"': '"Norm Bastydac"',
                   '"Джонатан Коен"': '"Jonathan Coen"',
                   '"Тобі Джонс Річард Армітедж Роджер Аллам Еймі Лу Вуд Розалінд Елізар Дірбла Моллой Пітер Уайт Анна Калдер-Маршалл"': '"Toby Jones Richard Armition Roger Allame Aimi Lu Wood Rosalind Elizar Dirbla Mollay Peter White Anna Kalder Marshall',
                   '"Хоакін Фенікс"': 'Hoaquin Phoenix', '"Леван Гелбахіані"': '"Levan Gelbachiana"',
                   '"Мелісса Маккарті': '"Melissa McCarta', '"Люсі Хейл"': '"Lucy Hale"',
                   '"Тімоті Шаламе': '"Timothy Shalyam', '"Крістіна Річчі"': '"Christina Rummy"',
                   '"Benedict Cumberbatch"': '"Benedickt Tsumbberbath"', '"Одесса Янг"': '"Odessa Young"',
                   '"Річард Гір"': '"Richard Mountain"', '"Claire Foy"': '"Tslire Foy"',
                   '"Джим Каммінґс"': '"Jim Kammints', '"Луї Гаррель"': '"Louis Garrel"',
                   '"Ханна Касулка"': '"Hannah Casulk"', '"Тіль Швайгер"': '"Til Shweiger"',
                   '"Саша Лусс"': '"Sasha Luss"', '"Валерія Бруні-Тедескі"': '"Valery Brunie Tedesque"',
                   '"Шей Мітчелл"': '"Shei Mitchell"', '"Гелен Міррен"': '"Helen Mirren"', '"Ліам Нісон': '"Liam Nison',
                   '"Тобін Белл"': '"Tobin Bell"', '"Блейк Лайвлі"': 'Blake Laylie', '"Енн Хетуей"': '"Ann Hetway"',
                   '"Anthony Hopkins"': '"Antony Hopkins"', '"Едріан Броуді"': 'Edrian Browe',
                   '"Джессі Баклі"': '"Jesse Buckley"', '"Джон Ф. Брунґот"': '"John F. Brungot"',
                   '"Ален Муссі"': '"Alain Mussy"', '"Дев Патель"': '"DEV Patel"', '"Жульєт Бінош"': '"Zhuliet Binos"',
                   '"Доміник Пінон"': '"Domestic Pinon"', '"Метт Деймон': '"Matt Damon',
                   '"Дайан Крюгер"': '"Diane Kruger"', '"Річард Карн"': '"Richard Carn"',
                   '"Джон Траволта"': '"John Travolta"', '"Кейт Бекінсейл"': '"Kate Beckinsale"',
                   '"Даніель Отой"': '"Daniel Thus"', '"Тімоті Шаламе"': '"Timothy Shalyam"',
                   '"Кріс Претт"': '"Chris Prett"', '"Benicio del Toro"': '"Benitio Del Toro"',
                   '"Софія Малі"': '"Sofia Mali"', '"DaniCraig"': 'Daniraig', '"Райан Гослінг"': '"Ryan Gosling"',
                   '"Кан Дон-вон"': '"Kan Don Won"', '"Джуліанна Мур': '"Giulianna Moore',
                   '"Анастасія Пустовіт"': '"Anastasia Pustovit"', '"Рем Керисі"': '"REM Keries"',
                   '"Emma Stone"': '"Emma Stone"', '"Джулія Робертс"': '"Julia Roberts"', '"Фін Літтл"': '"Fin Little"',
                   '"Едді Редмейн"': '"Eddie Redform"', '"Сильвестр Сталлоне"': '"Sylvester Stallone"',
                   '"James McAvoy"': '"Yams Mecavoy"', '"Карен Ґіллан"': '"Karen Gillan"',
                   '"Даніа Де Вільє"': '"Danea de Ville"', '"Cate Blanchett"': '"Chat Blanchett"',
                   '"Дені Бун"': '"Deni Bun"', '"Адам Сендлер"': '"Adam Sandler"',
                   '"Стефано Аккорсі"': '"Stephano Accorn"', '"Вігго Мортенсен"': '"Viggo Mortensen"',
                   '"Роберт Паттінсон"': '"Robert Pattinson"', '"Рассел Кроу"': '"Russell Crow"',
                   '"Закадровий голос - Іггі Поп"': '"Zamadov Voice - Iggie Pop"', '"Джемма Чан"': '"Jemma Chan"',
                   '"Базз Олдрін"': '"Bazz Oldrin"', '"Ніл МакДонаф"': '"Nile McDonaf"',
                   '"Тріне Дюрхольм"': '"Troin Durholm"',
                   '"П\'єр Карден Жан-Поль Готьє Філіп Штарк Наомі Кемпбелл Шерон Стоун го Пей Жан-Мішель Жарр Еліс Купер"': '"Pierre Carden Jean-Paul Gothie Philippa Starches Naomi Campbell Sharon Stone Stone Jean-Michel Jars Alice Kooper"',
                   '"Жерар Жюньо"': '"Gerard Juni"', '"Джеймс Франко"': '"James Franco"', '"Рона Мітра"': '"Mitra Ron"',
                   '"Мішель Вільямс"': '"Michelle Williams"', '"Дейзі Ексон"': '"Daisy Exon"',
                   '"Фрэнк Грилло"': '"FRENK GRILLA"', '"Джейкоб Трембле"': '"Jacob Tremble"',
                   '"ВІН ДІЗЕЛЬ"': '"Vin Diesel"', '"Зендея Коулман"': '"Zendei Kowlman"',
                   '"Даніель Отой "': '"Daniel Thus"', '"Пьерфранческо Фавіно"': '"Pierfrancho Favino"',
                   '"Пак Чханель"': '"Pak Chhanel"', '"Памела Андерсон"': '"Pamela Anderson"',
                   '"Чарлі Кокс"': '"Charlie Coke"', '"Холлі Хантер"': '"Holly Hunter"',
                   '"Олександра Квен"': '"Alexander Keven"', '"Бруно Саломон"': '"Bruno Salomon"',
                   '"Ентоні Гопкінс"': '"Anthony Gopkins"', '"Адам Драйвер': '"Adam Driver',
                   '"Валеріо Мастандреа"': '"Valio Mastandreea"', '"Анні-Фрід Люнгстад"': '"Anni-Fried Lungstad"',
                   '"Том Гарді"': '"Tom Gardy"', '"Марко Джалліні"': '"Marko Jallini"',
                   '"Мельвіль Пупо"': '"Melville Pullo"', '"Джонні Роуз"': '"Johnny Rose"'}

studios_dict = {'"Sony"': '"Sony Pictures Entertainment"',
                '"Warner Bros."': '"Warner Brothers Pictures"',
                '"Warner Bros. Pictures': '"Warner Brothers Pictures"'}

def lang_selector(language):
    if "Демонструється" in language:
        language = language.replace("Демонструється", "").strip()
    if "Англ" in language or "англ" in language or "aнгл" in language or "ориг" in language or "English" in language or "анлійс" in language:
        language = '"english"'
    if "росій" in language or "Росій" in language:
        language = '"russian"'
    if "Украинский" in language or "Українська" in language or "українська" in language:
        language = '"ukrainian"'
    if "мов" in language:
        language = language[:language.find("мов")]
    if "франц." in language or "Французька" in language or "Французька" in language or "французька" in language:
        language = '"french"'
    if "Німецька" in language or "німецька" in language:
        language = '"german"'
    if "китай" in language:
        language = '"chinese"'
    if "македон" in language:
        language = '"macedonian"'
    if "Італ" in language:
        language = '"italian"'
    if "Іспан" in language:
        language = '"spain"'
    if "грузин" in language:
        language = '"georgian"'
    if "корей" in language:
        language = '"korean"'
    if '""' in language:
        language = '"english"'
    return language


def transform_row(row):
    name, genre, duration, country, \
    studio, director, main_role, release, \
    rental_duration, language, age_limit, rating = row.split(',')

    if rating == 'nan':
        return None
    language = lang_selector(language)

    studio = studio.replace("d\'Images", "").strip()
    if "/" in studio:
        studio = studio[:studio.find("/")].strip()

    if studio in studios_dict.keys():
        studio = studios_dict[studio]

    duration = duration if len(duration) < 3 else int(duration[0]) * 60 + int(duration[1:])

    if "(" in director:
        director = director[:director.find("(")].strip() + '"'

    if "(" in main_role:
        main_role = main_role[:main_role.find("(")].strip() + '"'

    return ','.join([name, genres_dict[genre], str(duration), countries_dict[country.replace(".", "")], studio,
                     directors_dict[director], main_roles_dict[main_role], release, rental_duration, language,
                     age_limit, rating])
